var Bn=Object.defineProperty;var Le=(e,t)=>{for(var r in t)Bn(e,r,{get:t[r],enumerable:!0})};var zr={};Le(zr,{entropyToMnemonic:()=>jr,generateMnemonic:()=>po,mnemonicToEntropy:()=>$r,mnemonicToSeed:()=>go,mnemonicToSeedSync:()=>yo,validateMnemonic:()=>mo});function pe(e){if(!Number.isSafeInteger(e)||e<0)throw new Error(`positive integer expected, not ${e}`)}function kn(e){return e instanceof Uint8Array||e!=null&&typeof e=="object"&&e.constructor.name==="Uint8Array"}function V(e,...t){if(!kn(e))throw new Error("Uint8Array expected");if(t.length>0&&!t.includes(e.length))throw new Error(`Uint8Array expected of length ${t}, not of length=${e.length}`)}function Qe(e){if(typeof e!="function"||typeof e.create!="function")throw new Error("Hash should be wrapped by utils.wrapConstructor");pe(e.outputLen),pe(e.blockLen)}function Ke(e,t=!0){if(e.destroyed)throw new Error("Hash instance has been destroyed");if(t&&e.finished)throw new Error("Hash#digest() has already been called")}function rr(e,t){V(e);let r=t.outputLen;if(e.length<r)throw new Error(`digestInto() expects output buffer of length at least ${r}`)}var Fe=typeof globalThis=="object"&&"crypto"in globalThis?globalThis.crypto:void 0;var ee=e=>new DataView(e.buffer,e.byteOffset,e.byteLength),te=(e,t)=>e<<32-t|e>>>t,Pe=(e,t)=>e<<t|e>>>32-t>>>0,xi=new Uint8Array(new Uint32Array([287454020]).buffer)[0]===68;var An=Array.from({length:256},(e,t)=>t.toString(16).padStart(2,"0"));function or(e){V(e);let t="";for(let r=0;r<e.length;r++)t+=An[e[r]];return t}var le={_0:48,_9:57,_A:65,_F:70,_a:97,_f:102};function nr(e){if(e>=le._0&&e<=le._9)return e-le._0;if(e>=le._A&&e<=le._F)return e-(le._A-10);if(e>=le._a&&e<=le._f)return e-(le._a-10)}function ir(e){if(typeof e!="string")throw new Error("hex string expected, got "+typeof e);let t=e.length,r=t/2;if(t%2)throw new Error("padded hex string expected, got unpadded hex of length "+t);let n=new Uint8Array(r);for(let o=0,i=0;o<r;o++,i+=2){let a=nr(e.charCodeAt(i)),s=nr(e.charCodeAt(i+1));if(a===void 0||s===void 0){let c=e[i]+e[i+1];throw new Error('hex string expected, got non-hex character "'+c+'" at index '+i)}n[o]=a*16+s}return n}var Sn=async()=>{};async function sr(e,t,r){let n=Date.now();for(let o=0;o<e;o++){r(o);let i=Date.now()-n;i>=0&&i<t||(await Sn(),n+=i)}}function kt(e){if(typeof e!="string")throw new Error(`utf8ToBytes expected string, got ${typeof e}`);return new Uint8Array(new TextEncoder().encode(e))}function be(e){return typeof e=="string"&&(e=kt(e)),V(e),e}function _e(...e){let t=0;for(let n=0;n<e.length;n++){let o=e[n];V(o),t+=o.length}let r=new Uint8Array(t);for(let n=0,o=0;n<e.length;n++){let i=e[n];r.set(i,o),o+=i.length}return r}var Re=class{clone(){return this._cloneInto()}},In={}.toString;function ar(e,t){if(t!==void 0&&In.call(t)!=="[object Object]")throw new Error("Options should be object or undefined");return Object.assign(e,t)}function Te(e){let t=n=>e().update(be(n)).digest(),r=e();return t.outputLen=r.outputLen,t.blockLen=r.blockLen,t.create=()=>e(),t}function $e(e=32){if(Fe&&typeof Fe.getRandomValues=="function")return Fe.getRandomValues(new Uint8Array(e));throw new Error("crypto.getRandomValues must be defined")}var et=class extends Re{constructor(t,r){super(),this.finished=!1,this.destroyed=!1,Qe(t);let n=be(r);if(this.iHash=t.create(),typeof this.iHash.update!="function")throw new Error("Expected instance of class which extends utils.Hash");this.blockLen=this.iHash.blockLen,this.outputLen=this.iHash.outputLen;let o=this.blockLen,i=new Uint8Array(o);i.set(n.length>o?t.create().update(n).digest():n);for(let a=0;a<i.length;a++)i[a]^=54;this.iHash.update(i),this.oHash=t.create();for(let a=0;a<i.length;a++)i[a]^=106;this.oHash.update(i),i.fill(0)}update(t){return Ke(this),this.iHash.update(t),this}digestInto(t){Ke(this),V(t,this.outputLen),this.finished=!0,this.iHash.digestInto(t),this.oHash.update(t),this.oHash.digestInto(t),this.destroy()}digest(){let t=new Uint8Array(this.oHash.outputLen);return this.digestInto(t),t}_cloneInto(t){t||(t=Object.create(Object.getPrototypeOf(this),{}));let{oHash:r,iHash:n,finished:o,destroyed:i,blockLen:a,outputLen:s}=this;return t=t,t.finished=o,t.destroyed=i,t.blockLen=a,t.outputLen=s,t.oHash=r._cloneInto(t.oHash),t.iHash=n._cloneInto(t.iHash),t}destroy(){this.destroyed=!0,this.oHash.destroy(),this.iHash.destroy()}},me=(e,t,r)=>new et(e,t).update(r).digest();me.create=(e,t)=>new et(e,t);function cr(e,t,r,n){Qe(e);let o=ar({dkLen:32,asyncTick:10},n),{c:i,dkLen:a,asyncTick:s}=o;if(pe(i),pe(a),pe(s),i<1)throw new Error("PBKDF2: iterations (c) should be >= 1");let c=be(t),f=be(r),u=new Uint8Array(a),l=me.create(e,c),m=l._cloneInto().update(f);return{c:i,dkLen:a,asyncTick:s,DK:u,PRF:l,PRFSalt:m}}function lr(e,t,r,n,o){return e.destroy(),t.destroy(),n&&n.destroy(),o.fill(0),r}function fr(e,t,r,n){let{c:o,dkLen:i,DK:a,PRF:s,PRFSalt:c}=cr(e,t,r,n),f,u=new Uint8Array(4),l=ee(u),m=new Uint8Array(s.outputLen);for(let b=1,g=0;g<i;b++,g+=s.outputLen){let d=a.subarray(g,g+s.outputLen);l.setInt32(0,b,!1),(f=c._cloneInto(f)).update(u).digestInto(m),d.set(m.subarray(0,d.length));for(let h=1;h<o;h++){s._cloneInto(f).update(m).digestInto(m);for(let p=0;p<d.length;p++)d[p]^=m[p]}}return lr(s,c,a,f,m)}async function ur(e,t,r,n){let{c:o,dkLen:i,asyncTick:a,DK:s,PRF:c,PRFSalt:f}=cr(e,t,r,n),u,l=new Uint8Array(4),m=ee(l),b=new Uint8Array(c.outputLen);for(let g=1,d=0;d<i;g++,d+=c.outputLen){let h=s.subarray(d,d+c.outputLen);m.setInt32(0,g,!1),(u=f._cloneInto(u)).update(l).digestInto(b),h.set(b.subarray(0,h.length)),await sr(o-1,a,()=>{c._cloneInto(u).update(b).digestInto(b);for(let p=0;p<h.length;p++)h[p]^=b[p]})}return lr(c,f,s,u,b)}var pr={};Le(pr,{sha224:()=>Tn,sha256:()=>re});function Ln(e,t,r,n){if(typeof e.setBigUint64=="function")return e.setBigUint64(t,r,n);let o=BigInt(32),i=BigInt(4294967295),a=Number(r>>o&i),s=Number(r&i),c=n?4:0,f=n?0:4;e.setUint32(t+c,a,n),e.setUint32(t+f,s,n)}var dr=(e,t,r)=>e&t^~e&r,hr=(e,t,r)=>e&t^e&r^t&r,ge=class extends Re{constructor(t,r,n,o){super(),this.blockLen=t,this.outputLen=r,this.padOffset=n,this.isLE=o,this.finished=!1,this.length=0,this.pos=0,this.destroyed=!1,this.buffer=new Uint8Array(t),this.view=ee(this.buffer)}update(t){Ke(this);let{view:r,buffer:n,blockLen:o}=this;t=be(t);let i=t.length;for(let a=0;a<i;){let s=Math.min(o-this.pos,i-a);if(s===o){let c=ee(t);for(;o<=i-a;a+=o)this.process(c,a);continue}n.set(t.subarray(a,a+s),this.pos),this.pos+=s,a+=s,this.pos===o&&(this.process(r,0),this.pos=0)}return this.length+=t.length,this.roundClean(),this}digestInto(t){Ke(this),rr(t,this),this.finished=!0;let{buffer:r,view:n,blockLen:o,isLE:i}=this,{pos:a}=this;r[a++]=128,this.buffer.subarray(a).fill(0),this.padOffset>o-a&&(this.process(n,0),a=0);for(let l=a;l<o;l++)r[l]=0;Ln(n,o-8,BigInt(this.length*8),i),this.process(n,0);let s=ee(t),c=this.outputLen;if(c%4)throw new Error("_sha2: outputLen should be aligned to 32bit");let f=c/4,u=this.get();if(f>u.length)throw new Error("_sha2: outputLen bigger than state");for(let l=0;l<f;l++)s.setUint32(4*l,u[l],i)}digest(){let{buffer:t,outputLen:r}=this;this.digestInto(t);let n=t.slice(0,r);return this.destroy(),n}_cloneInto(t){t||(t=new this.constructor),t.set(...this.get());let{blockLen:r,buffer:n,length:o,finished:i,destroyed:a,pos:s}=this;return t.length=o,t.pos=s,t.finished=i,t.destroyed=a,o%r&&t.buffer.set(n),t}};var _n=new Uint32Array([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),ye=new Uint32Array([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]),we=new Uint32Array(64),tt=class extends ge{constructor(){super(64,32,8,!1),this.A=ye[0]|0,this.B=ye[1]|0,this.C=ye[2]|0,this.D=ye[3]|0,this.E=ye[4]|0,this.F=ye[5]|0,this.G=ye[6]|0,this.H=ye[7]|0}get(){let{A:t,B:r,C:n,D:o,E:i,F:a,G:s,H:c}=this;return[t,r,n,o,i,a,s,c]}set(t,r,n,o,i,a,s,c){this.A=t|0,this.B=r|0,this.C=n|0,this.D=o|0,this.E=i|0,this.F=a|0,this.G=s|0,this.H=c|0}process(t,r){for(let l=0;l<16;l++,r+=4)we[l]=t.getUint32(r,!1);for(let l=16;l<64;l++){let m=we[l-15],b=we[l-2],g=te(m,7)^te(m,18)^m>>>3,d=te(b,17)^te(b,19)^b>>>10;we[l]=d+we[l-7]+g+we[l-16]|0}let{A:n,B:o,C:i,D:a,E:s,F:c,G:f,H:u}=this;for(let l=0;l<64;l++){let m=te(s,6)^te(s,11)^te(s,25),b=u+m+dr(s,c,f)+_n[l]+we[l]|0,d=(te(n,2)^te(n,13)^te(n,22))+hr(n,o,i)|0;u=f,f=c,c=s,s=a+b|0,a=i,i=o,o=n,n=b+d|0}n=n+this.A|0,o=o+this.B|0,i=i+this.C|0,a=a+this.D|0,s=s+this.E|0,c=c+this.F|0,f=f+this.G|0,u=u+this.H|0,this.set(n,o,i,a,s,c,f,u)}roundClean(){we.fill(0)}destroy(){this.set(0,0,0,0,0,0,0,0),this.buffer.fill(0)}},At=class extends tt{constructor(){super(),this.A=-1056596264,this.B=914150663,this.C=812702999,this.D=-150054599,this.E=-4191439,this.F=1750603025,this.G=1694076839,this.H=-1090891868,this.outputLen=28}},re=Te(()=>new tt),Tn=Te(()=>new At);var rt=BigInt(4294967295),St=BigInt(32);function br(e,t=!1){return t?{h:Number(e&rt),l:Number(e>>St&rt)}:{h:Number(e>>St&rt)|0,l:Number(e&rt)|0}}function Hn(e,t=!1){let r=new Uint32Array(e.length),n=new Uint32Array(e.length);for(let o=0;o<e.length;o++){let{h:i,l:a}=br(e[o],t);[r[o],n[o]]=[i,a]}return[r,n]}var Un=(e,t)=>BigInt(e>>>0)<<St|BigInt(t>>>0),Cn=(e,t,r)=>e>>>r,On=(e,t,r)=>e<<32-r|t>>>r,Nn=(e,t,r)=>e>>>r|t<<32-r,qn=(e,t,r)=>e<<32-r|t>>>r,Kn=(e,t,r)=>e<<64-r|t>>>r-32,Rn=(e,t,r)=>e>>>r-32|t<<64-r,$n=(e,t)=>t,jn=(e,t)=>e,Dn=(e,t,r)=>e<<r|t>>>32-r,zn=(e,t,r)=>t<<r|e>>>32-r,Pn=(e,t,r)=>t<<r-32|e>>>64-r,Vn=(e,t,r)=>e<<r-32|t>>>64-r;function Mn(e,t,r,n){let o=(t>>>0)+(n>>>0);return{h:e+r+(o/2**32|0)|0,l:o|0}}var Zn=(e,t,r)=>(e>>>0)+(t>>>0)+(r>>>0),Gn=(e,t,r,n)=>t+r+n+(e/2**32|0)|0,Wn=(e,t,r,n)=>(e>>>0)+(t>>>0)+(r>>>0)+(n>>>0),Yn=(e,t,r,n,o)=>t+r+n+o+(e/2**32|0)|0,Xn=(e,t,r,n,o)=>(e>>>0)+(t>>>0)+(r>>>0)+(n>>>0)+(o>>>0),Jn=(e,t,r,n,o,i)=>t+r+n+o+i+(e/2**32|0)|0;var Qn={fromBig:br,split:Hn,toBig:Un,shrSH:Cn,shrSL:On,rotrSH:Nn,rotrSL:qn,rotrBH:Kn,rotrBL:Rn,rotr32H:$n,rotr32L:jn,rotlSH:Dn,rotlSL:zn,rotlBH:Pn,rotlBL:Vn,add:Mn,add3L:Zn,add3H:Gn,add4L:Wn,add4H:Yn,add5H:Jn,add5L:Xn},I=Qn;var[Fn,eo]=I.split(["0x428a2f98d728ae22","0x7137449123ef65cd","0xb5c0fbcfec4d3b2f","0xe9b5dba58189dbbc","0x3956c25bf348b538","0x59f111f1b605d019","0x923f82a4af194f9b","0xab1c5ed5da6d8118","0xd807aa98a3030242","0x12835b0145706fbe","0x243185be4ee4b28c","0x550c7dc3d5ffb4e2","0x72be5d74f27b896f","0x80deb1fe3b1696b1","0x9bdc06a725c71235","0xc19bf174cf692694","0xe49b69c19ef14ad2","0xefbe4786384f25e3","0x0fc19dc68b8cd5b5","0x240ca1cc77ac9c65","0x2de92c6f592b0275","0x4a7484aa6ea6e483","0x5cb0a9dcbd41fbd4","0x76f988da831153b5","0x983e5152ee66dfab","0xa831c66d2db43210","0xb00327c898fb213f","0xbf597fc7beef0ee4","0xc6e00bf33da88fc2","0xd5a79147930aa725","0x06ca6351e003826f","0x142929670a0e6e70","0x27b70a8546d22ffc","0x2e1b21385c26c926","0x4d2c6dfc5ac42aed","0x53380d139d95b3df","0x650a73548baf63de","0x766a0abb3c77b2a8","0x81c2c92e47edaee6","0x92722c851482353b","0xa2bfe8a14cf10364","0xa81a664bbc423001","0xc24b8b70d0f89791","0xc76c51a30654be30","0xd192e819d6ef5218","0xd69906245565a910","0xf40e35855771202a","0x106aa07032bbd1b8","0x19a4c116b8d2d0c8","0x1e376c085141ab53","0x2748774cdf8eeb99","0x34b0bcb5e19b48a8","0x391c0cb3c5c95a63","0x4ed8aa4ae3418acb","0x5b9cca4f7763e373","0x682e6ff3d6b2b8a3","0x748f82ee5defb2fc","0x78a5636f43172f60","0x84c87814a1f0ab72","0x8cc702081a6439ec","0x90befffa23631e28","0xa4506cebde82bde9","0xbef9a3f7b2c67915","0xc67178f2e372532b","0xca273eceea26619c","0xd186b8c721c0c207","0xeada7dd6cde0eb1e","0xf57d4f7fee6ed178","0x06f067aa72176fba","0x0a637dc5a2c898a6","0x113f9804bef90dae","0x1b710b35131c471b","0x28db77f523047d84","0x32caab7b40c72493","0x3c9ebe0a15c9bebc","0x431d67c49c100d4c","0x4cc5d4becb3e42b6","0x597f299cfc657e2a","0x5fcb6fab3ad6faec","0x6c44198c4a475817"].map(e=>BigInt(e))),xe=new Uint32Array(80),ve=new Uint32Array(80),It=class extends ge{constructor(){super(128,64,16,!1),this.Ah=1779033703,this.Al=-205731576,this.Bh=-1150833019,this.Bl=-2067093701,this.Ch=1013904242,this.Cl=-23791573,this.Dh=-1521486534,this.Dl=1595750129,this.Eh=1359893119,this.El=-1377402159,this.Fh=-1694144372,this.Fl=725511199,this.Gh=528734635,this.Gl=-79577749,this.Hh=1541459225,this.Hl=327033209}get(){let{Ah:t,Al:r,Bh:n,Bl:o,Ch:i,Cl:a,Dh:s,Dl:c,Eh:f,El:u,Fh:l,Fl:m,Gh:b,Gl:g,Hh:d,Hl:h}=this;return[t,r,n,o,i,a,s,c,f,u,l,m,b,g,d,h]}set(t,r,n,o,i,a,s,c,f,u,l,m,b,g,d,h){this.Ah=t|0,this.Al=r|0,this.Bh=n|0,this.Bl=o|0,this.Ch=i|0,this.Cl=a|0,this.Dh=s|0,this.Dl=c|0,this.Eh=f|0,this.El=u|0,this.Fh=l|0,this.Fl=m|0,this.Gh=b|0,this.Gl=g|0,this.Hh=d|0,this.Hl=h|0}process(t,r){for(let y=0;y<16;y++,r+=4)xe[y]=t.getUint32(r),ve[y]=t.getUint32(r+=4);for(let y=16;y<80;y++){let k=xe[y-15]|0,B=ve[y-15]|0,v=I.rotrSH(k,B,1)^I.rotrSH(k,B,8)^I.shrSH(k,B,7),A=I.rotrSL(k,B,1)^I.rotrSL(k,B,8)^I.shrSL(k,B,7),S=xe[y-2]|0,U=ve[y-2]|0,T=I.rotrSH(S,U,19)^I.rotrBH(S,U,61)^I.shrSH(S,U,6),_=I.rotrSL(S,U,19)^I.rotrBL(S,U,61)^I.shrSL(S,U,6),j=I.add4L(A,_,ve[y-7],ve[y-16]),z=I.add4H(j,v,T,xe[y-7],xe[y-16]);xe[y]=z|0,ve[y]=j|0}let{Ah:n,Al:o,Bh:i,Bl:a,Ch:s,Cl:c,Dh:f,Dl:u,Eh:l,El:m,Fh:b,Fl:g,Gh:d,Gl:h,Hh:p,Hl:x}=this;for(let y=0;y<80;y++){let k=I.rotrSH(l,m,14)^I.rotrSH(l,m,18)^I.rotrBH(l,m,41),B=I.rotrSL(l,m,14)^I.rotrSL(l,m,18)^I.rotrBL(l,m,41),v=l&b^~l&d,A=m&g^~m&h,S=I.add5L(x,B,A,eo[y],ve[y]),U=I.add5H(S,p,k,v,Fn[y],xe[y]),T=S|0,_=I.rotrSH(n,o,28)^I.rotrBH(n,o,34)^I.rotrBH(n,o,39),j=I.rotrSL(n,o,28)^I.rotrBL(n,o,34)^I.rotrBL(n,o,39),z=n&i^n&s^i&s,se=o&a^o&c^a&c;p=d|0,x=h|0,d=b|0,h=g|0,b=l|0,g=m|0,{h:l,l:m}=I.add(f|0,u|0,U|0,T|0),f=s|0,u=c|0,s=i|0,c=a|0,i=n|0,a=o|0;let w=I.add3L(T,j,se);n=I.add3H(w,U,_,z),o=w|0}({h:n,l:o}=I.add(this.Ah|0,this.Al|0,n|0,o|0)),{h:i,l:a}=I.add(this.Bh|0,this.Bl|0,i|0,a|0),{h:s,l:c}=I.add(this.Ch|0,this.Cl|0,s|0,c|0),{h:f,l:u}=I.add(this.Dh|0,this.Dl|0,f|0,u|0),{h:l,l:m}=I.add(this.Eh|0,this.El|0,l|0,m|0),{h:b,l:g}=I.add(this.Fh|0,this.Fl|0,b|0,g|0),{h:d,l:h}=I.add(this.Gh|0,this.Gl|0,d|0,h|0),{h:p,l:x}=I.add(this.Hh|0,this.Hl|0,p|0,x|0),this.set(n,o,i,a,s,c,f,u,l,m,b,g,d,h,p,x)}roundClean(){xe.fill(0),ve.fill(0)}destroy(){this.buffer.fill(0),this.set(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)}};var je=Te(()=>new It);var Nr={};Le(Nr,{assertNumber:()=>Ee,base16:()=>kr,base32:()=>Ar,base32crockford:()=>ro,base32hex:()=>to,base58:()=>Ze,base58check:()=>ao,base58flickr:()=>io,base58xmr:()=>Lr,base58xrp:()=>so,base64:()=>Sr,base64nopad:()=>no,base64url:()=>Ir,base64urlnopad:()=>oo,bech32:()=>co,bech32m:()=>lo,bytes:()=>uo,bytesToString:()=>Cr,createBase58check:()=>st,hex:()=>Hr,str:()=>fo,stringToBytes:()=>Or,utf8:()=>Tr,utils:()=>De});function Ee(e){if(!Number.isSafeInteger(e))throw new Error(`Wrong integer: ${e}`)}function Me(e){return e instanceof Uint8Array||e!=null&&typeof e=="object"&&e.constructor.name==="Uint8Array"}function W(...e){let t=i=>i,r=(i,a)=>s=>i(a(s)),n=e.map(i=>i.encode).reduceRight(r,t),o=e.map(i=>i.decode).reduce(r,t);return{encode:n,decode:o}}function X(e){return{encode:t=>{if(!Array.isArray(t)||t.length&&typeof t[0]!="number")throw new Error("alphabet.encode input should be an array of numbers");return t.map(r=>{if(r<0||r>=e.length)throw new Error(`Digit index outside alphabet: ${r} (alphabet: ${e.length})`);return e[r]})},decode:t=>{if(!Array.isArray(t)||t.length&&typeof t[0]!="string")throw new Error("alphabet.decode input should be array of strings");return t.map(r=>{if(typeof r!="string")throw new Error(`alphabet.decode: not string element=${r}`);let n=e.indexOf(r);if(n===-1)throw new Error(`Unknown letter: "${r}". Allowed: ${e}`);return n})}}}function J(e=""){if(typeof e!="string")throw new Error("join separator should be string");return{encode:t=>{if(!Array.isArray(t)||t.length&&typeof t[0]!="string")throw new Error("join.encode input should be array of strings");for(let r of t)if(typeof r!="string")throw new Error(`join.encode: non-string input=${r}`);return t.join(e)},decode:t=>{if(typeof t!="string")throw new Error("join.decode input should be string");return t.split(e)}}}function Ge(e,t="="){if(typeof t!="string")throw new Error("padding chr should be string");return{encode(r){if(!Array.isArray(r)||r.length&&typeof r[0]!="string")throw new Error("padding.encode input should be array of strings");for(let n of r)if(typeof n!="string")throw new Error(`padding.encode: non-string input=${n}`);for(;r.length*e%8;)r.push(t);return r},decode(r){if(!Array.isArray(r)||r.length&&typeof r[0]!="string")throw new Error("padding.encode input should be array of strings");for(let o of r)if(typeof o!="string")throw new Error(`padding.decode: non-string input=${o}`);let n=r.length;if(n*e%8)throw new Error("Invalid padding: string should have whole number of bytes");for(;n>0&&r[n-1]===t;n--)if(!((n-1)*e%8))throw new Error("Invalid padding: string has too much padding");return r.slice(0,n)}}}function xr(e){if(typeof e!="function")throw new Error("normalize fn should be function");return{encode:t=>t,decode:t=>e(t)}}function Lt(e,t,r){if(t<2)throw new Error(`convertRadix: wrong from=${t}, base cannot be less than 2`);if(r<2)throw new Error(`convertRadix: wrong to=${r}, base cannot be less than 2`);if(!Array.isArray(e))throw new Error("convertRadix: data should be array");if(!e.length)return[];let n=0,o=[],i=Array.from(e);for(i.forEach(a=>{if(a<0||a>=t)throw new Error(`Wrong integer: ${a}`)});;){let a=0,s=!0;for(let c=n;c<i.length;c++){let f=i[c],u=t*a+f;if(!Number.isSafeInteger(u)||t*a/t!==a||u-f!==t*a)throw new Error("convertRadix: carry overflow");a=u%r;let l=Math.floor(u/r);if(i[c]=l,!Number.isSafeInteger(l)||l*r+a!==u)throw new Error("convertRadix: carry overflow");if(s)l?s=!1:n=c;else continue}if(o.push(a),s)break}for(let a=0;a<e.length-1&&e[a]===0;a++)o.push(0);return o.reverse()}var vr=(e,t)=>t?vr(t,e%t):e,nt=(e,t)=>e+(t-vr(e,t));function ot(e,t,r,n){if(!Array.isArray(e))throw new Error("convertRadix2: data should be array");if(t<=0||t>32)throw new Error(`convertRadix2: wrong from=${t}`);if(r<=0||r>32)throw new Error(`convertRadix2: wrong to=${r}`);if(nt(t,r)>32)throw new Error(`convertRadix2: carry overflow from=${t} to=${r} carryBits=${nt(t,r)}`);let o=0,i=0,a=2**r-1,s=[];for(let c of e){if(c>=2**t)throw new Error(`convertRadix2: invalid data word=${c} from=${t}`);if(o=o<<t|c,i+t>32)throw new Error(`convertRadix2: carry overflow pos=${i} from=${t}`);for(i+=t;i>=r;i-=r)s.push((o>>i-r&a)>>>0);o&=2**i-1}if(o=o<<r-i&a,!n&&i>=t)throw new Error("Excess padding");if(!n&&o)throw new Error(`Non-zero padding: ${o}`);return n&&i>0&&s.push(o>>>0),s}function Er(e){return{encode:t=>{if(!Me(t))throw new Error("radix.encode input should be Uint8Array");return Lt(Array.from(t),2**8,e)},decode:t=>{if(!Array.isArray(t)||t.length&&typeof t[0]!="number")throw new Error("radix.decode input should be array of numbers");return Uint8Array.from(Lt(t,e,2**8))}}}function ne(e,t=!1){if(e<=0||e>32)throw new Error("radix2: bits should be in (0..32]");if(nt(8,e)>32||nt(e,8)>32)throw new Error("radix2: carry overflow");return{encode:r=>{if(!Me(r))throw new Error("radix2.encode input should be Uint8Array");return ot(Array.from(r),8,e,!t)},decode:r=>{if(!Array.isArray(r)||r.length&&typeof r[0]!="number")throw new Error("radix2.decode input should be array of numbers");return Uint8Array.from(ot(r,e,8,t))}}}function mr(e){if(typeof e!="function")throw new Error("unsafeWrapper fn should be function");return function(...t){try{return e.apply(null,t)}catch{}}}function Br(e,t){if(typeof t!="function")throw new Error("checksum fn should be function");return{encode(r){if(!Me(r))throw new Error("checksum.encode: input should be Uint8Array");let n=t(r).slice(0,e),o=new Uint8Array(r.length+e);return o.set(r),o.set(n,r.length),o},decode(r){if(!Me(r))throw new Error("checksum.decode: input should be Uint8Array");let n=r.slice(0,-e),o=t(n).slice(0,e),i=r.slice(-e);for(let a=0;a<e;a++)if(o[a]!==i[a])throw new Error("Invalid checksum");return n}}}var De={alphabet:X,chain:W,checksum:Br,convertRadix:Lt,convertRadix2:ot,radix:Er,radix2:ne,join:J,padding:Ge},kr=W(ne(4),X("0123456789ABCDEF"),J("")),Ar=W(ne(5),X("ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"),Ge(5),J("")),to=W(ne(5),X("0123456789ABCDEFGHIJKLMNOPQRSTUV"),Ge(5),J("")),ro=W(ne(5),X("0123456789ABCDEFGHJKMNPQRSTVWXYZ"),J(""),xr(e=>e.toUpperCase().replace(/O/g,"0").replace(/[IL]/g,"1"))),Sr=W(ne(6),X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),Ge(6),J("")),no=W(ne(6),X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"),J("")),Ir=W(ne(6),X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"),Ge(6),J("")),oo=W(ne(6),X("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"),J("")),Tt=e=>W(Er(58),X(e),J("")),Ze=Tt("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"),io=Tt("123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"),so=Tt("rpshnaf39wBUDNEGHJKLM4PQRST7VWXYZ2bcdeCg65jkm8oFqi1tuvAxyz"),gr=[0,2,3,5,6,7,9,10,11],Lr={encode(e){let t="";for(let r=0;r<e.length;r+=8){let n=e.subarray(r,r+8);t+=Ze.encode(n).padStart(gr[n.length],"1")}return t},decode(e){let t=[];for(let r=0;r<e.length;r+=11){let n=e.slice(r,r+11),o=gr.indexOf(n.length),i=Ze.decode(n);for(let a=0;a<i.length-o;a++)if(i[a]!==0)throw new Error("base58xmr: wrong padding");t=t.concat(Array.from(i.slice(i.length-o)))}return Uint8Array.from(t)}},st=e=>W(Br(4,t=>e(e(t))),Ze),ao=st,_t=W(X("qpzry9x8gf2tvdw0s3jn54khce6mua7l"),J("")),yr=[996825010,642813549,513874426,1027748829,705979059];function Ve(e){let t=e>>25,r=(e&33554431)<<5;for(let n=0;n<yr.length;n++)(t>>n&1)===1&&(r^=yr[n]);return r}function wr(e,t,r=1){let n=e.length,o=1;for(let i=0;i<n;i++){let a=e.charCodeAt(i);if(a<33||a>126)throw new Error(`Invalid prefix (${e})`);o=Ve(o)^a>>5}o=Ve(o);for(let i=0;i<n;i++)o=Ve(o)^e.charCodeAt(i)&31;for(let i of t)o=Ve(o)^i;for(let i=0;i<6;i++)o=Ve(o);return o^=r,_t.encode(ot([o%2**30],30,5,!1))}function _r(e){let t=e==="bech32"?1:734539939,r=ne(5),n=r.decode,o=r.encode,i=mr(n);function a(u,l,m=90){if(typeof u!="string")throw new Error(`bech32.encode prefix should be string, not ${typeof u}`);if(!Array.isArray(l)||l.length&&typeof l[0]!="number")throw new Error(`bech32.encode words should be array of numbers, not ${typeof l}`);if(u.length===0)throw new TypeError(`Invalid prefix length ${u.length}`);let b=u.length+7+l.length;if(m!==!1&&b>m)throw new TypeError(`Length ${b} exceeds limit ${m}`);let g=u.toLowerCase(),d=wr(g,l,t);return`${g}1${_t.encode(l)}${d}`}function s(u,l=90){if(typeof u!="string")throw new Error(`bech32.decode input should be string, not ${typeof u}`);if(u.length<8||l!==!1&&u.length>l)throw new TypeError(`Wrong string length: ${u.length} (${u}). Expected (8..${l})`);let m=u.toLowerCase();if(u!==m&&u!==u.toUpperCase())throw new Error("String must be lowercase or uppercase");let b=m.lastIndexOf("1");if(b===0||b===-1)throw new Error('Letter "1" must be present between prefix and data only');let g=m.slice(0,b),d=m.slice(b+1);if(d.length<6)throw new Error("Data must be at least 6 characters long");let h=_t.decode(d).slice(0,-6),p=wr(g,h,t);if(!d.endsWith(p))throw new Error(`Invalid checksum in ${u}: expected "${p}"`);return{prefix:g,words:h}}let c=mr(s);function f(u){let{prefix:l,words:m}=s(u,!1);return{prefix:l,words:m,bytes:n(m)}}return{encode:a,decode:s,decodeToBytes:f,decodeUnsafe:c,fromWords:n,fromWordsUnsafe:i,toWords:o}}var co=_r("bech32"),lo=_r("bech32m"),Tr={encode:e=>new TextDecoder().decode(e),decode:e=>new TextEncoder().encode(e)},Hr=W(ne(4),X("0123456789abcdef"),J(""),xr(e=>{if(typeof e!="string"||e.length%2)throw new TypeError(`hex.decode: expected string, got ${typeof e} with length ${e.length}`);return e.toLowerCase()})),it={utf8:Tr,hex:Hr,base16:kr,base32:Ar,base64:Sr,base64url:Ir,base58:Ze,base58xmr:Lr},Ur="Invalid encoding type. Available types: utf8, hex, base16, base32, base64, base64url, base58, base58xmr",Cr=(e,t)=>{if(typeof e!="string"||!it.hasOwnProperty(e))throw new TypeError(Ur);if(!Me(t))throw new TypeError("bytesToString() expects Uint8Array");return it[e].encode(t)},fo=Cr,Or=(e,t)=>{if(!it.hasOwnProperty(e))throw new TypeError(Ur);if(typeof t!="string")throw new TypeError("stringToBytes() expects string");return it[e].decode(t)},uo=Or;var ho=e=>e[0]==="\u3042\u3044\u3053\u304F\u3057\u3093";function qr(e){if(typeof e!="string")throw new TypeError(`Invalid mnemonic type: ${typeof e}`);return e.normalize("NFKD")}function Ht(e){let t=qr(e),r=t.split(" ");if(![12,15,18,21,24].includes(r.length))throw new Error("Invalid mnemonic");return{nfkd:t,words:r}}function Kr(e){V(e,16,20,24,28,32)}function po(e,t=128){if(pe(t),t%32!==0||t>256)throw new TypeError("Invalid entropy");return jr($e(t/8),e)}var bo=e=>{let t=8-e.length/4;return new Uint8Array([re(e)[0]>>t<<t])};function Rr(e){if(!Array.isArray(e)||e.length!==2048||typeof e[0]!="string")throw new Error("Wordlist: expected array of 2048 strings");return e.forEach(t=>{if(typeof t!="string")throw new Error(`Wordlist: non-string element: ${t}`)}),De.chain(De.checksum(1,bo),De.radix2(11,!0),De.alphabet(e))}function $r(e,t){let{words:r}=Ht(e),n=Rr(t).decode(r);return Kr(n),n}function jr(e,t){return Kr(e),Rr(t).encode(e).join(ho(t)?"\u3000":" ")}function mo(e,t){try{$r(e,t)}catch{return!1}return!0}var Dr=e=>qr(`mnemonic${e}`);function go(e,t=""){return ur(je,Ht(e).nfkd,Dr(t),{c:2048,dkLen:64})}function yo(e,t=""){return fr(je,Ht(e).nfkd,Dr(t),{c:2048,dkLen:64})}var wo=`abandon
ability
able
about
above
absent
absorb
abstract
absurd
abuse
access
accident
account
accuse
achieve
acid
acoustic
acquire
across
act
action
actor
actress
actual
adapt
add
addict
address
adjust
admit
adult
advance
advice
aerobic
affair
afford
afraid
again
age
agent
agree
ahead
aim
air
airport
aisle
alarm
album
alcohol
alert
alien
all
alley
allow
almost
alone
alpha
already
also
alter
always
amateur
amazing
among
amount
amused
analyst
anchor
ancient
anger
angle
angry
animal
ankle
announce
annual
another
answer
antenna
antique
anxiety
any
apart
apology
appear
apple
approve
april
arch
arctic
area
arena
argue
arm
armed
armor
army
around
arrange
arrest
arrive
arrow
art
artefact
artist
artwork
ask
aspect
assault
asset
assist
assume
asthma
athlete
atom
attack
attend
attitude
attract
auction
audit
august
aunt
author
auto
autumn
average
avocado
avoid
awake
aware
away
awesome
awful
awkward
axis
baby
bachelor
bacon
badge
bag
balance
balcony
ball
bamboo
banana
banner
bar
barely
bargain
barrel
base
basic
basket
battle
beach
bean
beauty
because
become
beef
before
begin
behave
behind
believe
below
belt
bench
benefit
best
betray
better
between
beyond
bicycle
bid
bike
bind
biology
bird
birth
bitter
black
blade
blame
blanket
blast
bleak
bless
blind
blood
blossom
blouse
blue
blur
blush
board
boat
body
boil
bomb
bone
bonus
book
boost
border
boring
borrow
boss
bottom
bounce
box
boy
bracket
brain
brand
brass
brave
bread
breeze
brick
bridge
brief
bright
bring
brisk
broccoli
broken
bronze
broom
brother
brown
brush
bubble
buddy
budget
buffalo
build
bulb
bulk
bullet
bundle
bunker
burden
burger
burst
bus
business
busy
butter
buyer
buzz
cabbage
cabin
cable
cactus
cage
cake
call
calm
camera
camp
can
canal
cancel
candy
cannon
canoe
canvas
canyon
capable
capital
captain
car
carbon
card
cargo
carpet
carry
cart
case
cash
casino
castle
casual
cat
catalog
catch
category
cattle
caught
cause
caution
cave
ceiling
celery
cement
census
century
cereal
certain
chair
chalk
champion
change
chaos
chapter
charge
chase
chat
cheap
check
cheese
chef
cherry
chest
chicken
chief
child
chimney
choice
choose
chronic
chuckle
chunk
churn
cigar
cinnamon
circle
citizen
city
civil
claim
clap
clarify
claw
clay
clean
clerk
clever
click
client
cliff
climb
clinic
clip
clock
clog
close
cloth
cloud
clown
club
clump
cluster
clutch
coach
coast
coconut
code
coffee
coil
coin
collect
color
column
combine
come
comfort
comic
common
company
concert
conduct
confirm
congress
connect
consider
control
convince
cook
cool
copper
copy
coral
core
corn
correct
cost
cotton
couch
country
couple
course
cousin
cover
coyote
crack
cradle
craft
cram
crane
crash
crater
crawl
crazy
cream
credit
creek
crew
cricket
crime
crisp
critic
crop
cross
crouch
crowd
crucial
cruel
cruise
crumble
crunch
crush
cry
crystal
cube
culture
cup
cupboard
curious
current
curtain
curve
cushion
custom
cute
cycle
dad
damage
damp
dance
danger
daring
dash
daughter
dawn
day
deal
debate
debris
decade
december
decide
decline
decorate
decrease
deer
defense
define
defy
degree
delay
deliver
demand
demise
denial
dentist
deny
depart
depend
deposit
depth
deputy
derive
describe
desert
design
desk
despair
destroy
detail
detect
develop
device
devote
diagram
dial
diamond
diary
dice
diesel
diet
differ
digital
dignity
dilemma
dinner
dinosaur
direct
dirt
disagree
discover
disease
dish
dismiss
disorder
display
distance
divert
divide
divorce
dizzy
doctor
document
dog
doll
dolphin
domain
donate
donkey
donor
door
dose
double
dove
draft
dragon
drama
drastic
draw
dream
dress
drift
drill
drink
drip
drive
drop
drum
dry
duck
dumb
dune
during
dust
dutch
duty
dwarf
dynamic
eager
eagle
early
earn
earth
easily
east
easy
echo
ecology
economy
edge
edit
educate
effort
egg
eight
either
elbow
elder
electric
elegant
element
elephant
elevator
elite
else
embark
embody
embrace
emerge
emotion
employ
empower
empty
enable
enact
end
endless
endorse
enemy
energy
enforce
engage
engine
enhance
enjoy
enlist
enough
enrich
enroll
ensure
enter
entire
entry
envelope
episode
equal
equip
era
erase
erode
erosion
error
erupt
escape
essay
essence
estate
eternal
ethics
evidence
evil
evoke
evolve
exact
example
excess
exchange
excite
exclude
excuse
execute
exercise
exhaust
exhibit
exile
exist
exit
exotic
expand
expect
expire
explain
expose
express
extend
extra
eye
eyebrow
fabric
face
faculty
fade
faint
faith
fall
false
fame
family
famous
fan
fancy
fantasy
farm
fashion
fat
fatal
father
fatigue
fault
favorite
feature
february
federal
fee
feed
feel
female
fence
festival
fetch
fever
few
fiber
fiction
field
figure
file
film
filter
final
find
fine
finger
finish
fire
firm
first
fiscal
fish
fit
fitness
fix
flag
flame
flash
flat
flavor
flee
flight
flip
float
flock
floor
flower
fluid
flush
fly
foam
focus
fog
foil
fold
follow
food
foot
force
forest
forget
fork
fortune
forum
forward
fossil
foster
found
fox
fragile
frame
frequent
fresh
friend
fringe
frog
front
frost
frown
frozen
fruit
fuel
fun
funny
furnace
fury
future
gadget
gain
galaxy
gallery
game
gap
garage
garbage
garden
garlic
garment
gas
gasp
gate
gather
gauge
gaze
general
genius
genre
gentle
genuine
gesture
ghost
giant
gift
giggle
ginger
giraffe
girl
give
glad
glance
glare
glass
glide
glimpse
globe
gloom
glory
glove
glow
glue
goat
goddess
gold
good
goose
gorilla
gospel
gossip
govern
gown
grab
grace
grain
grant
grape
grass
gravity
great
green
grid
grief
grit
grocery
group
grow
grunt
guard
guess
guide
guilt
guitar
gun
gym
habit
hair
half
hammer
hamster
hand
happy
harbor
hard
harsh
harvest
hat
have
hawk
hazard
head
health
heart
heavy
hedgehog
height
hello
helmet
help
hen
hero
hidden
high
hill
hint
hip
hire
history
hobby
hockey
hold
hole
holiday
hollow
home
honey
hood
hope
horn
horror
horse
hospital
host
hotel
hour
hover
hub
huge
human
humble
humor
hundred
hungry
hunt
hurdle
hurry
hurt
husband
hybrid
ice
icon
idea
identify
idle
ignore
ill
illegal
illness
image
imitate
immense
immune
impact
impose
improve
impulse
inch
include
income
increase
index
indicate
indoor
industry
infant
inflict
inform
inhale
inherit
initial
inject
injury
inmate
inner
innocent
input
inquiry
insane
insect
inside
inspire
install
intact
interest
into
invest
invite
involve
iron
island
isolate
issue
item
ivory
jacket
jaguar
jar
jazz
jealous
jeans
jelly
jewel
job
join
joke
journey
joy
judge
juice
jump
jungle
junior
junk
just
kangaroo
keen
keep
ketchup
key
kick
kid
kidney
kind
kingdom
kiss
kit
kitchen
kite
kitten
kiwi
knee
knife
knock
know
lab
label
labor
ladder
lady
lake
lamp
language
laptop
large
later
latin
laugh
laundry
lava
law
lawn
lawsuit
layer
lazy
leader
leaf
learn
leave
lecture
left
leg
legal
legend
leisure
lemon
lend
length
lens
leopard
lesson
letter
level
liar
liberty
library
license
life
lift
light
like
limb
limit
link
lion
liquid
list
little
live
lizard
load
loan
lobster
local
lock
logic
lonely
long
loop
lottery
loud
lounge
love
loyal
lucky
luggage
lumber
lunar
lunch
luxury
lyrics
machine
mad
magic
magnet
maid
mail
main
major
make
mammal
man
manage
mandate
mango
mansion
manual
maple
marble
march
margin
marine
market
marriage
mask
mass
master
match
material
math
matrix
matter
maximum
maze
meadow
mean
measure
meat
mechanic
medal
media
melody
melt
member
memory
mention
menu
mercy
merge
merit
merry
mesh
message
metal
method
middle
midnight
milk
million
mimic
mind
minimum
minor
minute
miracle
mirror
misery
miss
mistake
mix
mixed
mixture
mobile
model
modify
mom
moment
monitor
monkey
monster
month
moon
moral
more
morning
mosquito
mother
motion
motor
mountain
mouse
move
movie
much
muffin
mule
multiply
muscle
museum
mushroom
music
must
mutual
myself
mystery
myth
naive
name
napkin
narrow
nasty
nation
nature
near
neck
need
negative
neglect
neither
nephew
nerve
nest
net
network
neutral
never
news
next
nice
night
noble
noise
nominee
noodle
normal
north
nose
notable
note
nothing
notice
novel
now
nuclear
number
nurse
nut
oak
obey
object
oblige
obscure
observe
obtain
obvious
occur
ocean
october
odor
off
offer
office
often
oil
okay
old
olive
olympic
omit
once
one
onion
online
only
open
opera
opinion
oppose
option
orange
orbit
orchard
order
ordinary
organ
orient
original
orphan
ostrich
other
outdoor
outer
output
outside
oval
oven
over
own
owner
oxygen
oyster
ozone
pact
paddle
page
pair
palace
palm
panda
panel
panic
panther
paper
parade
parent
park
parrot
party
pass
patch
path
patient
patrol
pattern
pause
pave
payment
peace
peanut
pear
peasant
pelican
pen
penalty
pencil
people
pepper
perfect
permit
person
pet
phone
photo
phrase
physical
piano
picnic
picture
piece
pig
pigeon
pill
pilot
pink
pioneer
pipe
pistol
pitch
pizza
place
planet
plastic
plate
play
please
pledge
pluck
plug
plunge
poem
poet
point
polar
pole
police
pond
pony
pool
popular
portion
position
possible
post
potato
pottery
poverty
powder
power
practice
praise
predict
prefer
prepare
present
pretty
prevent
price
pride
primary
print
priority
prison
private
prize
problem
process
produce
profit
program
project
promote
proof
property
prosper
protect
proud
provide
public
pudding
pull
pulp
pulse
pumpkin
punch
pupil
puppy
purchase
purity
purpose
purse
push
put
puzzle
pyramid
quality
quantum
quarter
question
quick
quit
quiz
quote
rabbit
raccoon
race
rack
radar
radio
rail
rain
raise
rally
ramp
ranch
random
range
rapid
rare
rate
rather
raven
raw
razor
ready
real
reason
rebel
rebuild
recall
receive
recipe
record
recycle
reduce
reflect
reform
refuse
region
regret
regular
reject
relax
release
relief
rely
remain
remember
remind
remove
render
renew
rent
reopen
repair
repeat
replace
report
require
rescue
resemble
resist
resource
response
result
retire
retreat
return
reunion
reveal
review
reward
rhythm
rib
ribbon
rice
rich
ride
ridge
rifle
right
rigid
ring
riot
ripple
risk
ritual
rival
river
road
roast
robot
robust
rocket
romance
roof
rookie
room
rose
rotate
rough
round
route
royal
rubber
rude
rug
rule
run
runway
rural
sad
saddle
sadness
safe
sail
salad
salmon
salon
salt
salute
same
sample
sand
satisfy
satoshi
sauce
sausage
save
say
scale
scan
scare
scatter
scene
scheme
school
science
scissors
scorpion
scout
scrap
screen
script
scrub
sea
search
season
seat
second
secret
section
security
seed
seek
segment
select
sell
seminar
senior
sense
sentence
series
service
session
settle
setup
seven
shadow
shaft
shallow
share
shed
shell
sheriff
shield
shift
shine
ship
shiver
shock
shoe
shoot
shop
short
shoulder
shove
shrimp
shrug
shuffle
shy
sibling
sick
side
siege
sight
sign
silent
silk
silly
silver
similar
simple
since
sing
siren
sister
situate
six
size
skate
sketch
ski
skill
skin
skirt
skull
slab
slam
sleep
slender
slice
slide
slight
slim
slogan
slot
slow
slush
small
smart
smile
smoke
smooth
snack
snake
snap
sniff
snow
soap
soccer
social
sock
soda
soft
solar
soldier
solid
solution
solve
someone
song
soon
sorry
sort
soul
sound
soup
source
south
space
spare
spatial
spawn
speak
special
speed
spell
spend
sphere
spice
spider
spike
spin
spirit
split
spoil
sponsor
spoon
sport
spot
spray
spread
spring
spy
square
squeeze
squirrel
stable
stadium
staff
stage
stairs
stamp
stand
start
state
stay
steak
steel
stem
step
stereo
stick
still
sting
stock
stomach
stone
stool
story
stove
strategy
street
strike
strong
struggle
student
stuff
stumble
style
subject
submit
subway
success
such
sudden
suffer
sugar
suggest
suit
summer
sun
sunny
sunset
super
supply
supreme
sure
surface
surge
surprise
surround
survey
suspect
sustain
swallow
swamp
swap
swarm
swear
sweet
swift
swim
swing
switch
sword
symbol
symptom
syrup
system
table
tackle
tag
tail
talent
talk
tank
tape
target
task
taste
tattoo
taxi
teach
team
tell
ten
tenant
tennis
tent
term
test
text
thank
that
theme
then
theory
there
they
thing
this
thought
three
thrive
throw
thumb
thunder
ticket
tide
tiger
tilt
timber
time
tiny
tip
tired
tissue
title
toast
tobacco
today
toddler
toe
together
toilet
token
tomato
tomorrow
tone
tongue
tonight
tool
tooth
top
topic
topple
torch
tornado
tortoise
toss
total
tourist
toward
tower
town
toy
track
trade
traffic
tragic
train
transfer
trap
trash
travel
tray
treat
tree
trend
trial
tribe
trick
trigger
trim
trip
trophy
trouble
truck
true
truly
trumpet
trust
truth
try
tube
tuition
tumble
tuna
tunnel
turkey
turn
turtle
twelve
twenty
twice
twin
twist
two
type
typical
ugly
umbrella
unable
unaware
uncle
uncover
under
undo
unfair
unfold
unhappy
uniform
unique
unit
universe
unknown
unlock
until
unusual
unveil
update
upgrade
uphold
upon
upper
upset
urban
urge
usage
use
used
useful
useless
usual
utility
vacant
vacuum
vague
valid
valley
valve
van
vanish
vapor
various
vast
vault
vehicle
velvet
vendor
venture
venue
verb
verify
version
very
vessel
veteran
viable
vibrant
vicious
victory
video
view
village
vintage
violin
virtual
virus
visa
visit
visual
vital
vivid
vocal
voice
void
volcano
volume
vote
voyage
wage
wagon
wait
walk
wall
walnut
want
warfare
warm
warrior
wash
wasp
waste
water
wave
way
wealth
weapon
wear
weasel
weather
web
wedding
weekend
weird
welcome
west
wet
whale
what
wheat
wheel
when
where
whip
whisper
wide
width
wife
wild
will
win
window
wine
wing
wink
winner
winter
wire
wisdom
wise
wish
witness
wolf
woman
wonder
wood
wool
word
work
world
worry
worth
wrap
wreck
wrestle
wrist
write
wrong
yard
year
yellow
you
young
youth
zebra
zero
zone
zoo`.split(`
`);var En={};Le(En,{HARDENED_OFFSET:()=>Et,HDKey:()=>Qt});var Zr={};Le(Zr,{RIPEMD160:()=>ct,ripemd160:()=>Ot});var xo=new Uint8Array([7,4,13,1,10,6,15,3,12,0,9,5,2,14,11,8]),Vr=new Uint8Array(new Array(16).fill(0).map((e,t)=>t)),vo=Vr.map(e=>(9*e+5)%16),Ut=[Vr],Ct=[vo];for(let e=0;e<4;e++)for(let t of[Ut,Ct])t.push(t[e].map(r=>xo[r]));var Mr=[[11,14,15,12,5,8,7,9,11,13,14,15,6,7,9,8],[12,13,11,15,6,9,9,7,12,15,11,13,7,8,7,7],[13,15,14,11,7,7,6,8,13,14,13,12,5,5,6,9],[14,11,12,14,8,6,5,5,15,12,15,14,9,9,8,6],[15,12,13,13,9,5,8,6,14,11,12,11,8,6,5,5]].map(e=>new Uint8Array(e)),Eo=Ut.map((e,t)=>e.map(r=>Mr[t][r])),Bo=Ct.map((e,t)=>e.map(r=>Mr[t][r])),ko=new Uint32Array([0,1518500249,1859775393,2400959708,2840853838]),Ao=new Uint32Array([1352829926,1548603684,1836072691,2053994217,0]);function Pr(e,t,r,n){return e===0?t^r^n:e===1?t&r|~t&n:e===2?(t|~r)^n:e===3?t&n|r&~n:t^(r|~n)}var at=new Uint32Array(16),ct=class extends ge{constructor(){super(64,20,8,!0),this.h0=1732584193,this.h1=-271733879,this.h2=-1732584194,this.h3=271733878,this.h4=-1009589776}get(){let{h0:t,h1:r,h2:n,h3:o,h4:i}=this;return[t,r,n,o,i]}set(t,r,n,o,i){this.h0=t|0,this.h1=r|0,this.h2=n|0,this.h3=o|0,this.h4=i|0}process(t,r){for(let b=0;b<16;b++,r+=4)at[b]=t.getUint32(r,!0);let n=this.h0|0,o=n,i=this.h1|0,a=i,s=this.h2|0,c=s,f=this.h3|0,u=f,l=this.h4|0,m=l;for(let b=0;b<5;b++){let g=4-b,d=ko[b],h=Ao[b],p=Ut[b],x=Ct[b],y=Eo[b],k=Bo[b];for(let B=0;B<16;B++){let v=Pe(n+Pr(b,i,s,f)+at[p[B]]+d,y[B])+l|0;n=l,l=f,f=Pe(s,10)|0,s=i,i=v}for(let B=0;B<16;B++){let v=Pe(o+Pr(g,a,c,u)+at[x[B]]+h,k[B])+m|0;o=m,m=u,u=Pe(c,10)|0,c=a,a=v}}this.set(this.h1+s+u|0,this.h2+f+m|0,this.h3+l+o|0,this.h4+n+a|0,this.h0+i+c|0)}roundClean(){at.fill(0)}destroy(){this.destroyed=!0,this.buffer.fill(0),this.set(0,0,0,0,0)}},Ot=Te(()=>new ct);var xn={};Le(xn,{encodeToCurve:()=>fi,hashToCurve:()=>li,schnorr:()=>si,secp256k1:()=>M});var Rt={};Le(Rt,{abytes:()=>Q,bitGet:()=>Ho,bitLen:()=>To,bitMask:()=>Ye,bitSet:()=>Uo,bytesToHex:()=>He,bytesToNumberBE:()=>K,bytesToNumberLE:()=>ft,concatBytes:()=>P,createHmacDrbg:()=>Kt,ensureBytes:()=>R,equalBytes:()=>_o,hexToBytes:()=>Ue,hexToNumber:()=>qt,isBytes:()=>Be,numberToBytesBE:()=>oe,numberToBytesLE:()=>ut,numberToHexUnpadded:()=>Xr,numberToVarBytesBE:()=>Lo,utf8ToBytes:()=>We,validateObject:()=>ce});var Yr=BigInt(0),lt=BigInt(1),So=BigInt(2);function Be(e){return e instanceof Uint8Array||e!=null&&typeof e=="object"&&e.constructor.name==="Uint8Array"}function Q(e){if(!Be(e))throw new Error("Uint8Array expected")}var Io=Array.from({length:256},(e,t)=>t.toString(16).padStart(2,"0"));function He(e){Q(e);let t="";for(let r=0;r<e.length;r++)t+=Io[e[r]];return t}function Xr(e){let t=e.toString(16);return t.length&1?`0${t}`:t}function qt(e){if(typeof e!="string")throw new Error("hex string expected, got "+typeof e);return BigInt(e===""?"0":`0x${e}`)}var fe={_0:48,_9:57,_A:65,_F:70,_a:97,_f:102};function Gr(e){if(e>=fe._0&&e<=fe._9)return e-fe._0;if(e>=fe._A&&e<=fe._F)return e-(fe._A-10);if(e>=fe._a&&e<=fe._f)return e-(fe._a-10)}function Ue(e){if(typeof e!="string")throw new Error("hex string expected, got "+typeof e);let t=e.length,r=t/2;if(t%2)throw new Error("padded hex string expected, got unpadded hex of length "+t);let n=new Uint8Array(r);for(let o=0,i=0;o<r;o++,i+=2){let a=Gr(e.charCodeAt(i)),s=Gr(e.charCodeAt(i+1));if(a===void 0||s===void 0){let c=e[i]+e[i+1];throw new Error('hex string expected, got non-hex character "'+c+'" at index '+i)}n[o]=a*16+s}return n}function K(e){return qt(He(e))}function ft(e){return Q(e),qt(He(Uint8Array.from(e).reverse()))}function oe(e,t){return Ue(e.toString(16).padStart(t*2,"0"))}function ut(e,t){return oe(e,t).reverse()}function Lo(e){return Ue(Xr(e))}function R(e,t,r){let n;if(typeof t=="string")try{n=Ue(t)}catch(i){throw new Error(`${e} must be valid hex string, got "${t}". Cause: ${i}`)}else if(Be(t))n=Uint8Array.from(t);else throw new Error(`${e} must be hex string or Uint8Array`);let o=n.length;if(typeof r=="number"&&o!==r)throw new Error(`${e} expected ${r} bytes, got ${o}`);return n}function P(...e){let t=0;for(let n=0;n<e.length;n++){let o=e[n];Q(o),t+=o.length}let r=new Uint8Array(t);for(let n=0,o=0;n<e.length;n++){let i=e[n];r.set(i,o),o+=i.length}return r}function _o(e,t){if(e.length!==t.length)return!1;let r=0;for(let n=0;n<e.length;n++)r|=e[n]^t[n];return r===0}function We(e){if(typeof e!="string")throw new Error(`utf8ToBytes expected string, got ${typeof e}`);return new Uint8Array(new TextEncoder().encode(e))}function To(e){let t;for(t=0;e>Yr;e>>=lt,t+=1);return t}function Ho(e,t){return e>>BigInt(t)&lt}function Uo(e,t,r){return e|(r?lt:Yr)<<BigInt(t)}var Ye=e=>(So<<BigInt(e-1))-lt,Nt=e=>new Uint8Array(e),Wr=e=>Uint8Array.from(e);function Kt(e,t,r){if(typeof e!="number"||e<2)throw new Error("hashLen must be a number");if(typeof t!="number"||t<2)throw new Error("qByteLen must be a number");if(typeof r!="function")throw new Error("hmacFn must be a function");let n=Nt(e),o=Nt(e),i=0,a=()=>{n.fill(1),o.fill(0),i=0},s=(...l)=>r(o,n,...l),c=(l=Nt())=>{o=s(Wr([0]),l),n=s(),l.length!==0&&(o=s(Wr([1]),l),n=s())},f=()=>{if(i++>=1e3)throw new Error("drbg: tried 1000 values");let l=0,m=[];for(;l<t;){n=s();let b=n.slice();m.push(b),l+=n.length}return P(...m)};return(l,m)=>{a(),c(l);let b;for(;!(b=m(f()));)c();return a(),b}}var Co={bigint:e=>typeof e=="bigint",function:e=>typeof e=="function",boolean:e=>typeof e=="boolean",string:e=>typeof e=="string",stringOrUint8Array:e=>typeof e=="string"||Be(e),isSafeInteger:e=>Number.isSafeInteger(e),array:e=>Array.isArray(e),field:(e,t)=>t.Fp.isValid(e),hash:e=>typeof e=="function"&&Number.isSafeInteger(e.outputLen)};function ce(e,t,r={}){let n=(o,i,a)=>{let s=Co[i];if(typeof s!="function")throw new Error(`Invalid validator "${i}", expected function`);let c=e[o];if(!(a&&c===void 0)&&!s(c,e))throw new Error(`Invalid param ${String(o)}=${c} (${typeof c}), expected ${i}`)};for(let[o,i]of Object.entries(t))n(o,i,!1);for(let[o,i]of Object.entries(r))n(o,i,!0);return e}var $=BigInt(0),N=BigInt(1),Ce=BigInt(2),Oo=BigInt(3),$t=BigInt(4),Jr=BigInt(5),Qr=BigInt(8),No=BigInt(9),qo=BigInt(16);function O(e,t){let r=e%t;return r>=$?r:t+r}function Ko(e,t,r){if(r<=$||t<$)throw new Error("Expected power/modulo > 0");if(r===N)return $;let n=N;for(;t>$;)t&N&&(n=n*e%r),e=e*e%r,t>>=N;return n}function Y(e,t,r){let n=e;for(;t-- >$;)n*=n,n%=r;return n}function dt(e,t){if(e===$||t<=$)throw new Error(`invert: expected positive integers, got n=${e} mod=${t}`);let r=O(e,t),n=t,o=$,i=N,a=N,s=$;for(;r!==$;){let f=n/r,u=n%r,l=o-a*f,m=i-s*f;n=r,r=u,o=a,i=s,a=l,s=m}if(n!==N)throw new Error("invert: does not exist");return O(o,t)}function Ro(e){let t=(e-N)/Ce,r,n,o;for(r=e-N,n=0;r%Ce===$;r/=Ce,n++);for(o=Ce;o<e&&Ko(o,t,e)!==e-N;o++);if(n===1){let a=(e+N)/$t;return function(c,f){let u=c.pow(f,a);if(!c.eql(c.sqr(u),f))throw new Error("Cannot find square root");return u}}let i=(r+N)/Ce;return function(s,c){if(s.pow(c,t)===s.neg(s.ONE))throw new Error("Cannot find square root");let f=n,u=s.pow(s.mul(s.ONE,o),r),l=s.pow(c,i),m=s.pow(c,r);for(;!s.eql(m,s.ONE);){if(s.eql(m,s.ZERO))return s.ZERO;let b=1;for(let d=s.sqr(m);b<f&&!s.eql(d,s.ONE);b++)d=s.sqr(d);let g=s.pow(u,N<<BigInt(f-b-1));u=s.sqr(g),l=s.mul(l,g),m=s.mul(m,u),f=b}return l}}function $o(e){if(e%$t===Oo){let t=(e+N)/$t;return function(n,o){let i=n.pow(o,t);if(!n.eql(n.sqr(i),o))throw new Error("Cannot find square root");return i}}if(e%Qr===Jr){let t=(e-Jr)/Qr;return function(n,o){let i=n.mul(o,Ce),a=n.pow(i,t),s=n.mul(o,a),c=n.mul(n.mul(s,Ce),a),f=n.mul(s,n.sub(c,n.ONE));if(!n.eql(n.sqr(f),o))throw new Error("Cannot find square root");return f}}return e%qo,Ro(e)}var jo=["create","isValid","is0","neg","inv","sqrt","sqr","eql","add","sub","mul","pow","div","addN","subN","mulN","sqrN"];function ht(e){let t={ORDER:"bigint",MASK:"bigint",BYTES:"isSafeInteger",BITS:"isSafeInteger"},r=jo.reduce((n,o)=>(n[o]="function",n),t);return ce(e,r)}function Do(e,t,r){if(r<$)throw new Error("Expected power > 0");if(r===$)return e.ONE;if(r===N)return t;let n=e.ONE,o=t;for(;r>$;)r&N&&(n=e.mul(n,o)),o=e.sqr(o),r>>=N;return n}function zo(e,t){let r=new Array(t.length),n=t.reduce((i,a,s)=>e.is0(a)?i:(r[s]=i,e.mul(i,a)),e.ONE),o=e.inv(n);return t.reduceRight((i,a,s)=>e.is0(a)?i:(r[s]=e.mul(i,r[s]),e.mul(i,a)),o),r}function jt(e,t){let r=t!==void 0?t:e.toString(2).length,n=Math.ceil(r/8);return{nBitLength:r,nByteLength:n}}function Fr(e,t,r=!1,n={}){if(e<=$)throw new Error(`Expected Field ORDER > 0, got ${e}`);let{nBitLength:o,nByteLength:i}=jt(e,t);if(i>2048)throw new Error("Field lengths over 2048 bytes are not supported");let a=$o(e),s=Object.freeze({ORDER:e,BITS:o,BYTES:i,MASK:Ye(o),ZERO:$,ONE:N,create:c=>O(c,e),isValid:c=>{if(typeof c!="bigint")throw new Error(`Invalid field element: expected bigint, got ${typeof c}`);return $<=c&&c<e},is0:c=>c===$,isOdd:c=>(c&N)===N,neg:c=>O(-c,e),eql:(c,f)=>c===f,sqr:c=>O(c*c,e),add:(c,f)=>O(c+f,e),sub:(c,f)=>O(c-f,e),mul:(c,f)=>O(c*f,e),pow:(c,f)=>Do(s,c,f),div:(c,f)=>O(c*dt(f,e),e),sqrN:c=>c*c,addN:(c,f)=>c+f,subN:(c,f)=>c-f,mulN:(c,f)=>c*f,inv:c=>dt(c,e),sqrt:n.sqrt||(c=>a(s,c)),invertBatch:c=>zo(s,c),cmov:(c,f,u)=>u?f:c,toBytes:c=>r?ut(c,i):oe(c,i),fromBytes:c=>{if(c.length!==i)throw new Error(`Fp.fromBytes: expected ${i}, got ${c.length}`);return r?ft(c):K(c)}});return Object.freeze(s)}function en(e){if(typeof e!="bigint")throw new Error("field order must be bigint");let t=e.toString(2).length;return Math.ceil(t/8)}function Dt(e){let t=en(e);return t+Math.ceil(t/2)}function tn(e,t,r=!1){let n=e.length,o=en(t),i=Dt(t);if(n<16||n<i||n>1024)throw new Error(`expected ${i}-1024 bytes of input, got ${n}`);let a=r?K(e):ft(e),s=O(a,t-N)+N;return r?ut(s,o):oe(s,o)}var Vo=BigInt(0),zt=BigInt(1);function rn(e,t){let r=(o,i)=>{let a=i.negate();return o?a:i},n=o=>{let i=Math.ceil(t/o)+1,a=2**(o-1);return{windows:i,windowSize:a}};return{constTimeNegate:r,unsafeLadder(o,i){let a=e.ZERO,s=o;for(;i>Vo;)i&zt&&(a=a.add(s)),s=s.double(),i>>=zt;return a},precomputeWindow(o,i){let{windows:a,windowSize:s}=n(i),c=[],f=o,u=f;for(let l=0;l<a;l++){u=f,c.push(u);for(let m=1;m<s;m++)u=u.add(f),c.push(u);f=u.double()}return c},wNAF(o,i,a){let{windows:s,windowSize:c}=n(o),f=e.ZERO,u=e.BASE,l=BigInt(2**o-1),m=2**o,b=BigInt(o);for(let g=0;g<s;g++){let d=g*c,h=Number(a&l);a>>=b,h>c&&(h-=m,a+=zt);let p=d,x=d+Math.abs(h)-1,y=g%2!==0,k=h<0;h===0?u=u.add(r(y,i[p])):f=f.add(r(k,i[x]))}return{p:f,f:u}},wNAFCached(o,i,a,s){let c=o._WINDOW_SIZE||1,f=i.get(o);return f||(f=this.precomputeWindow(o,c),c!==1&&i.set(o,s(f))),this.wNAF(c,f,a)}}}function Pt(e){return ht(e.Fp),ce(e,{n:"bigint",h:"bigint",Gx:"field",Gy:"field"},{nBitLength:"isSafeInteger",nByteLength:"isSafeInteger"}),Object.freeze({...jt(e.n,e.nBitLength),...e,p:e.Fp.ORDER})}function Mo(e){let t=Pt(e);ce(t,{a:"field",b:"field"},{allowedPrivateKeyLengths:"array",wrapPrivateKey:"boolean",isTorsionFree:"function",clearCofactor:"function",allowInfinityPoint:"boolean",fromBytes:"function",toBytes:"function"});let{endo:r,Fp:n,a:o}=t;if(r){if(!n.eql(o,n.ZERO))throw new Error("Endomorphism can only be defined for Koblitz curves that have a=0");if(typeof r!="object"||typeof r.beta!="bigint"||typeof r.splitScalar!="function")throw new Error("Expected endomorphism with beta: bigint and splitScalar: function")}return Object.freeze({...t})}var{bytesToNumberBE:Zo,hexToBytes:Go}=Rt,Oe={Err:class extends Error{constructor(t=""){super(t)}},_parseInt(e){let{Err:t}=Oe;if(e.length<2||e[0]!==2)throw new t("Invalid signature integer tag");let r=e[1],n=e.subarray(2,r+2);if(!r||n.length!==r)throw new t("Invalid signature integer: wrong length");if(n[0]&128)throw new t("Invalid signature integer: negative");if(n[0]===0&&!(n[1]&128))throw new t("Invalid signature integer: unnecessary leading zero");return{d:Zo(n),l:e.subarray(r+2)}},toSig(e){let{Err:t}=Oe,r=typeof e=="string"?Go(e):e;Q(r);let n=r.length;if(n<2||r[0]!=48)throw new t("Invalid signature tag");if(r[1]!==n-2)throw new t("Invalid signature: incorrect length");let{d:o,l:i}=Oe._parseInt(r.subarray(2)),{d:a,l:s}=Oe._parseInt(i);if(s.length)throw new t("Invalid signature: left bytes after parsing");return{r:o,s:a}},hexFromSig(e){let t=f=>Number.parseInt(f[0],16)&8?"00"+f:f,r=f=>{let u=f.toString(16);return u.length&1?`0${u}`:u},n=t(r(e.s)),o=t(r(e.r)),i=n.length/2,a=o.length/2,s=r(i),c=r(a);return`30${r(a+i+4)}02${c}${o}02${s}${n}`}},ie=BigInt(0),q=BigInt(1),ke=BigInt(2),pt=BigInt(3),nn=BigInt(4);function Wo(e){let t=Mo(e),{Fp:r}=t,n=t.toBytes||((g,d,h)=>{let p=d.toAffine();return P(Uint8Array.from([4]),r.toBytes(p.x),r.toBytes(p.y))}),o=t.fromBytes||(g=>{let d=g.subarray(1),h=r.fromBytes(d.subarray(0,r.BYTES)),p=r.fromBytes(d.subarray(r.BYTES,2*r.BYTES));return{x:h,y:p}});function i(g){let{a:d,b:h}=t,p=r.sqr(g),x=r.mul(p,g);return r.add(r.add(x,r.mul(g,d)),h)}if(!r.eql(r.sqr(t.Gy),i(t.Gx)))throw new Error("bad generator point: equation left != right");function a(g){return typeof g=="bigint"&&ie<g&&g<t.n}function s(g){if(!a(g))throw new Error("Expected valid bigint: 0 < bigint < curve.n")}function c(g){let{allowedPrivateKeyLengths:d,nByteLength:h,wrapPrivateKey:p,n:x}=t;if(d&&typeof g!="bigint"){if(Be(g)&&(g=He(g)),typeof g!="string"||!d.includes(g.length))throw new Error("Invalid key");g=g.padStart(h*2,"0")}let y;try{y=typeof g=="bigint"?g:K(R("private key",g,h))}catch{throw new Error(`private key must be ${h} bytes, hex or bigint, not ${typeof g}`)}return p&&(y=O(y,x)),s(y),y}let f=new Map;function u(g){if(!(g instanceof l))throw new Error("ProjectivePoint expected")}class l{constructor(d,h,p){if(this.px=d,this.py=h,this.pz=p,d==null||!r.isValid(d))throw new Error("x required");if(h==null||!r.isValid(h))throw new Error("y required");if(p==null||!r.isValid(p))throw new Error("z required")}static fromAffine(d){let{x:h,y:p}=d||{};if(!d||!r.isValid(h)||!r.isValid(p))throw new Error("invalid affine point");if(d instanceof l)throw new Error("projective point not allowed");let x=y=>r.eql(y,r.ZERO);return x(h)&&x(p)?l.ZERO:new l(h,p,r.ONE)}get x(){return this.toAffine().x}get y(){return this.toAffine().y}static normalizeZ(d){let h=r.invertBatch(d.map(p=>p.pz));return d.map((p,x)=>p.toAffine(h[x])).map(l.fromAffine)}static fromHex(d){let h=l.fromAffine(o(R("pointHex",d)));return h.assertValidity(),h}static fromPrivateKey(d){return l.BASE.multiply(c(d))}_setWindowSize(d){this._WINDOW_SIZE=d,f.delete(this)}assertValidity(){if(this.is0()){if(t.allowInfinityPoint&&!r.is0(this.py))return;throw new Error("bad point: ZERO")}let{x:d,y:h}=this.toAffine();if(!r.isValid(d)||!r.isValid(h))throw new Error("bad point: x or y not FE");let p=r.sqr(h),x=i(d);if(!r.eql(p,x))throw new Error("bad point: equation left != right");if(!this.isTorsionFree())throw new Error("bad point: not in prime-order subgroup")}hasEvenY(){let{y:d}=this.toAffine();if(r.isOdd)return!r.isOdd(d);throw new Error("Field doesn't support isOdd")}equals(d){u(d);let{px:h,py:p,pz:x}=this,{px:y,py:k,pz:B}=d,v=r.eql(r.mul(h,B),r.mul(y,x)),A=r.eql(r.mul(p,B),r.mul(k,x));return v&&A}negate(){return new l(this.px,r.neg(this.py),this.pz)}double(){let{a:d,b:h}=t,p=r.mul(h,pt),{px:x,py:y,pz:k}=this,B=r.ZERO,v=r.ZERO,A=r.ZERO,S=r.mul(x,x),U=r.mul(y,y),T=r.mul(k,k),_=r.mul(x,y);return _=r.add(_,_),A=r.mul(x,k),A=r.add(A,A),B=r.mul(d,A),v=r.mul(p,T),v=r.add(B,v),B=r.sub(U,v),v=r.add(U,v),v=r.mul(B,v),B=r.mul(_,B),A=r.mul(p,A),T=r.mul(d,T),_=r.sub(S,T),_=r.mul(d,_),_=r.add(_,A),A=r.add(S,S),S=r.add(A,S),S=r.add(S,T),S=r.mul(S,_),v=r.add(v,S),T=r.mul(y,k),T=r.add(T,T),S=r.mul(T,_),B=r.sub(B,S),A=r.mul(T,U),A=r.add(A,A),A=r.add(A,A),new l(B,v,A)}add(d){u(d);let{px:h,py:p,pz:x}=this,{px:y,py:k,pz:B}=d,v=r.ZERO,A=r.ZERO,S=r.ZERO,U=t.a,T=r.mul(t.b,pt),_=r.mul(h,y),j=r.mul(p,k),z=r.mul(x,B),se=r.add(h,p),w=r.add(y,k);se=r.mul(se,w),w=r.add(_,j),se=r.sub(se,w),w=r.add(h,x);let E=r.add(y,B);return w=r.mul(w,E),E=r.add(_,z),w=r.sub(w,E),E=r.add(p,x),v=r.add(k,B),E=r.mul(E,v),v=r.add(j,z),E=r.sub(E,v),S=r.mul(U,w),v=r.mul(T,z),S=r.add(v,S),v=r.sub(j,S),S=r.add(j,S),A=r.mul(v,S),j=r.add(_,_),j=r.add(j,_),z=r.mul(U,z),w=r.mul(T,w),j=r.add(j,z),z=r.sub(_,z),z=r.mul(U,z),w=r.add(w,z),_=r.mul(j,w),A=r.add(A,_),_=r.mul(E,w),v=r.mul(se,v),v=r.sub(v,_),_=r.mul(se,j),S=r.mul(E,S),S=r.add(S,_),new l(v,A,S)}subtract(d){return this.add(d.negate())}is0(){return this.equals(l.ZERO)}wNAF(d){return b.wNAFCached(this,f,d,h=>{let p=r.invertBatch(h.map(x=>x.pz));return h.map((x,y)=>x.toAffine(p[y])).map(l.fromAffine)})}multiplyUnsafe(d){let h=l.ZERO;if(d===ie)return h;if(s(d),d===q)return this;let{endo:p}=t;if(!p)return b.unsafeLadder(this,d);let{k1neg:x,k1:y,k2neg:k,k2:B}=p.splitScalar(d),v=h,A=h,S=this;for(;y>ie||B>ie;)y&q&&(v=v.add(S)),B&q&&(A=A.add(S)),S=S.double(),y>>=q,B>>=q;return x&&(v=v.negate()),k&&(A=A.negate()),A=new l(r.mul(A.px,p.beta),A.py,A.pz),v.add(A)}multiply(d){s(d);let h=d,p,x,{endo:y}=t;if(y){let{k1neg:k,k1:B,k2neg:v,k2:A}=y.splitScalar(h),{p:S,f:U}=this.wNAF(B),{p:T,f:_}=this.wNAF(A);S=b.constTimeNegate(k,S),T=b.constTimeNegate(v,T),T=new l(r.mul(T.px,y.beta),T.py,T.pz),p=S.add(T),x=U.add(_)}else{let{p:k,f:B}=this.wNAF(h);p=k,x=B}return l.normalizeZ([p,x])[0]}multiplyAndAddUnsafe(d,h,p){let x=l.BASE,y=(B,v)=>v===ie||v===q||!B.equals(x)?B.multiplyUnsafe(v):B.multiply(v),k=y(this,h).add(y(d,p));return k.is0()?void 0:k}toAffine(d){let{px:h,py:p,pz:x}=this,y=this.is0();d==null&&(d=y?r.ONE:r.inv(x));let k=r.mul(h,d),B=r.mul(p,d),v=r.mul(x,d);if(y)return{x:r.ZERO,y:r.ZERO};if(!r.eql(v,r.ONE))throw new Error("invZ was invalid");return{x:k,y:B}}isTorsionFree(){let{h:d,isTorsionFree:h}=t;if(d===q)return!0;if(h)return h(l,this);throw new Error("isTorsionFree() has not been declared for the elliptic curve")}clearCofactor(){let{h:d,clearCofactor:h}=t;return d===q?this:h?h(l,this):this.multiplyUnsafe(t.h)}toRawBytes(d=!0){return this.assertValidity(),n(l,this,d)}toHex(d=!0){return He(this.toRawBytes(d))}}l.BASE=new l(t.Gx,t.Gy,r.ONE),l.ZERO=new l(r.ZERO,r.ONE,r.ZERO);let m=t.nBitLength,b=rn(l,t.endo?Math.ceil(m/2):m);return{CURVE:t,ProjectivePoint:l,normPrivateKeyToScalar:c,weierstrassEquation:i,isWithinCurveOrder:a}}function Yo(e){let t=Pt(e);return ce(t,{hash:"hash",hmac:"function",randomBytes:"function"},{bits2int:"function",bits2int_modN:"function",lowS:"boolean"}),Object.freeze({lowS:!0,...t})}function on(e){let t=Yo(e),{Fp:r,n}=t,o=r.BYTES+1,i=2*r.BYTES+1;function a(w){return ie<w&&w<r.ORDER}function s(w){return O(w,n)}function c(w){return dt(w,n)}let{ProjectivePoint:f,normPrivateKeyToScalar:u,weierstrassEquation:l,isWithinCurveOrder:m}=Wo({...t,toBytes(w,E,L){let C=E.toAffine(),H=r.toBytes(C.x),D=P;return L?D(Uint8Array.from([E.hasEvenY()?2:3]),H):D(Uint8Array.from([4]),H,r.toBytes(C.y))},fromBytes(w){let E=w.length,L=w[0],C=w.subarray(1);if(E===o&&(L===2||L===3)){let H=K(C);if(!a(H))throw new Error("Point is not on curve");let D=l(H),Z;try{Z=r.sqrt(D)}catch(F){let de=F instanceof Error?": "+F.message:"";throw new Error("Point is not on curve"+de)}let G=(Z&q)===q;return(L&1)===1!==G&&(Z=r.neg(Z)),{x:H,y:Z}}else if(E===i&&L===4){let H=r.fromBytes(C.subarray(0,r.BYTES)),D=r.fromBytes(C.subarray(r.BYTES,2*r.BYTES));return{x:H,y:D}}else throw new Error(`Point of length ${E} was invalid. Expected ${o} compressed bytes or ${i} uncompressed bytes`)}}),b=w=>He(oe(w,t.nByteLength));function g(w){let E=n>>q;return w>E}function d(w){return g(w)?s(-w):w}let h=(w,E,L)=>K(w.slice(E,L));class p{constructor(E,L,C){this.r=E,this.s=L,this.recovery=C,this.assertValidity()}static fromCompact(E){let L=t.nByteLength;return E=R("compactSignature",E,L*2),new p(h(E,0,L),h(E,L,2*L))}static fromDER(E){let{r:L,s:C}=Oe.toSig(R("DER",E));return new p(L,C)}assertValidity(){if(!m(this.r))throw new Error("r must be 0 < r < CURVE.n");if(!m(this.s))throw new Error("s must be 0 < s < CURVE.n")}addRecoveryBit(E){return new p(this.r,this.s,E)}recoverPublicKey(E){let{r:L,s:C,recovery:H}=this,D=A(R("msgHash",E));if(H==null||![0,1,2,3].includes(H))throw new Error("recovery id invalid");let Z=H===2||H===3?L+t.n:L;if(Z>=r.ORDER)throw new Error("recovery id 2 or 3 invalid");let G=(H&1)===0?"02":"03",ue=f.fromHex(G+b(Z)),F=c(Z),de=s(-D*F),ze=s(C*F),he=f.BASE.multiplyAndAddUnsafe(ue,de,ze);if(!he)throw new Error("point at infinify");return he.assertValidity(),he}hasHighS(){return g(this.s)}normalizeS(){return this.hasHighS()?new p(this.r,s(-this.s),this.recovery):this}toDERRawBytes(){return Ue(this.toDERHex())}toDERHex(){return Oe.hexFromSig({r:this.r,s:this.s})}toCompactRawBytes(){return Ue(this.toCompactHex())}toCompactHex(){return b(this.r)+b(this.s)}}let x={isValidPrivateKey(w){try{return u(w),!0}catch{return!1}},normPrivateKeyToScalar:u,randomPrivateKey:()=>{let w=Dt(t.n);return tn(t.randomBytes(w),t.n)},precompute(w=8,E=f.BASE){return E._setWindowSize(w),E.multiply(BigInt(3)),E}};function y(w,E=!0){return f.fromPrivateKey(w).toRawBytes(E)}function k(w){let E=Be(w),L=typeof w=="string",C=(E||L)&&w.length;return E?C===o||C===i:L?C===2*o||C===2*i:w instanceof f}function B(w,E,L=!0){if(k(w))throw new Error("first arg must be private key");if(!k(E))throw new Error("second arg must be public key");return f.fromHex(E).multiply(u(w)).toRawBytes(L)}let v=t.bits2int||function(w){let E=K(w),L=w.length*8-t.nBitLength;return L>0?E>>BigInt(L):E},A=t.bits2int_modN||function(w){return s(v(w))},S=Ye(t.nBitLength);function U(w){if(typeof w!="bigint")throw new Error("bigint expected");if(!(ie<=w&&w<S))throw new Error(`bigint expected < 2^${t.nBitLength}`);return oe(w,t.nByteLength)}function T(w,E,L=_){if(["recovered","canonical"].some(Ie=>Ie in L))throw new Error("sign() legacy options not supported");let{hash:C,randomBytes:H}=t,{lowS:D,prehash:Z,extraEntropy:G}=L;D==null&&(D=!0),w=R("msgHash",w),Z&&(w=R("prehashed msgHash",C(w)));let ue=A(w),F=u(E),de=[U(F),U(ue)];if(G!=null&&G!==!1){let Ie=G===!0?H(r.BYTES):G;de.push(R("extraEntropy",Ie))}let ze=P(...de),he=ue;function Bt(Ie){let Ne=v(Ie);if(!m(Ne))return;let Ft=c(Ne),ae=f.BASE.multiply(Ne).toAffine(),qe=s(ae.x);if(qe===ie)return;let Je=s(Ft*s(he+qe*F));if(Je===ie)return;let er=(ae.x===qe?0:2)|Number(ae.y&q),tr=Je;return D&&g(Je)&&(tr=d(Je),er^=1),new p(qe,tr,er)}return{seed:ze,k2sig:Bt}}let _={lowS:t.lowS,prehash:!1},j={lowS:t.lowS,prehash:!1};function z(w,E,L=_){let{seed:C,k2sig:H}=T(w,E,L),D=t;return Kt(D.hash.outputLen,D.nByteLength,D.hmac)(C,H)}f.BASE._setWindowSize(8);function se(w,E,L,C=j){let H=w;if(E=R("msgHash",E),L=R("publicKey",L),"strict"in C)throw new Error("options.strict was renamed to lowS");let{lowS:D,prehash:Z}=C,G,ue;try{if(typeof H=="string"||Be(H))try{G=p.fromDER(H)}catch(ae){if(!(ae instanceof Oe.Err))throw ae;G=p.fromCompact(H)}else if(typeof H=="object"&&typeof H.r=="bigint"&&typeof H.s=="bigint"){let{r:ae,s:qe}=H;G=new p(ae,qe)}else throw new Error("PARSE");ue=f.fromHex(L)}catch(ae){if(ae.message==="PARSE")throw new Error("signature must be Signature instance, Uint8Array or hex string");return!1}if(D&&G.hasHighS())return!1;Z&&(E=t.hash(E));let{r:F,s:de}=G,ze=A(E),he=c(de),Bt=s(ze*he),Ie=s(F*he),Ne=f.BASE.multiplyAndAddUnsafe(ue,Bt,Ie)?.toAffine();return Ne?s(Ne.x)===F:!1}return{CURVE:t,getPublicKey:y,getSharedSecret:B,sign:z,verify:se,ProjectivePoint:f,Signature:p,utils:x}}function Xo(e,t){let r=e.ORDER,n=ie;for(let g=r-q;g%ke===ie;g/=ke)n+=q;let o=n,i=ke<<o-q-q,a=i*ke,s=(r-q)/a,c=(s-q)/ke,f=a-q,u=i,l=e.pow(t,s),m=e.pow(t,(s+q)/ke),b=(g,d)=>{let h=l,p=e.pow(d,f),x=e.sqr(p);x=e.mul(x,d);let y=e.mul(g,x);y=e.pow(y,c),y=e.mul(y,p),p=e.mul(y,d),x=e.mul(y,g);let k=e.mul(x,p);y=e.pow(k,u);let B=e.eql(y,e.ONE);p=e.mul(x,m),y=e.mul(k,h),x=e.cmov(p,x,B),k=e.cmov(y,k,B);for(let v=o;v>q;v--){let A=v-ke;A=ke<<A-q;let S=e.pow(k,A),U=e.eql(S,e.ONE);p=e.mul(x,h),h=e.mul(h,h),S=e.mul(k,h),x=e.cmov(p,x,U),k=e.cmov(S,k,U)}return{isValid:B,value:x}};if(e.ORDER%nn===pt){let g=(e.ORDER-pt)/nn,d=e.sqrt(e.neg(t));b=(h,p)=>{let x=e.sqr(p),y=e.mul(h,p);x=e.mul(x,y);let k=e.pow(x,g);k=e.mul(k,y);let B=e.mul(k,d),v=e.mul(e.sqr(k),p),A=e.eql(v,h),S=e.cmov(B,k,A);return{isValid:A,value:S}}}return b}function sn(e,t){if(ht(e),!e.isValid(t.A)||!e.isValid(t.B)||!e.isValid(t.Z))throw new Error("mapToCurveSimpleSWU: invalid opts");let r=Xo(e,t.Z);if(!e.isOdd)throw new Error("Fp.isOdd is not implemented!");return n=>{let o,i,a,s,c,f,u,l;o=e.sqr(n),o=e.mul(o,t.Z),i=e.sqr(o),i=e.add(i,o),a=e.add(i,e.ONE),a=e.mul(a,t.B),s=e.cmov(t.Z,e.neg(i),!e.eql(i,e.ZERO)),s=e.mul(s,t.A),i=e.sqr(a),f=e.sqr(s),c=e.mul(f,t.A),i=e.add(i,c),i=e.mul(i,a),f=e.mul(f,s),c=e.mul(f,t.B),i=e.add(i,c),u=e.mul(o,a);let{isValid:m,value:b}=r(i,f);l=e.mul(o,n),l=e.mul(l,b),u=e.cmov(u,a,m),l=e.cmov(l,b,m);let g=e.isOdd(n)===e.isOdd(l);return l=e.cmov(e.neg(l),l,g),u=e.div(u,s),{x:u,y:l}}}var Jo=K;function Ae(e,t){if(e<0||e>=1<<8*t)throw new Error(`bad I2OSP call: value=${e} length=${t}`);let r=Array.from({length:t}).fill(0);for(let n=t-1;n>=0;n--)r[n]=e&255,e>>>=8;return new Uint8Array(r)}function Qo(e,t){let r=new Uint8Array(e.length);for(let n=0;n<e.length;n++)r[n]=e[n]^t[n];return r}function Vt(e){if(!Number.isSafeInteger(e))throw new Error("number expected")}function Fo(e,t,r,n){Q(e),Q(t),Vt(r),t.length>255&&(t=n(P(We("H2C-OVERSIZE-DST-"),t)));let{outputLen:o,blockLen:i}=n,a=Math.ceil(r/o);if(a>255)throw new Error("Invalid xmd length");let s=P(t,Ae(t.length,1)),c=Ae(0,i),f=Ae(r,2),u=new Array(a),l=n(P(c,e,f,Ae(0,1),s));u[0]=n(P(l,Ae(1,1),s));for(let b=1;b<=a;b++){let g=[Qo(l,u[b-1]),Ae(b+1,1),s];u[b]=n(P(...g))}return P(...u).slice(0,r)}function ei(e,t,r,n,o){if(Q(e),Q(t),Vt(r),t.length>255){let i=Math.ceil(2*n/8);t=o.create({dkLen:i}).update(We("H2C-OVERSIZE-DST-")).update(t).digest()}if(r>65535||t.length>255)throw new Error("expand_message_xof: invalid lenInBytes");return o.create({dkLen:r}).update(e).update(Ae(r,2)).update(t).update(Ae(t.length,1)).digest()}function an(e,t,r){ce(r,{DST:"stringOrUint8Array",p:"bigint",m:"isSafeInteger",k:"isSafeInteger",hash:"hash"});let{p:n,k:o,m:i,hash:a,expand:s,DST:c}=r;Q(e),Vt(t);let f=typeof c=="string"?We(c):c,u=n.toString(2).length,l=Math.ceil((u+o)/8),m=t*i*l,b;if(s==="xmd")b=Fo(e,f,m,a);else if(s==="xof")b=ei(e,f,m,o,a);else if(s==="_internal_pass")b=e;else throw new Error('expand must be "xmd" or "xof"');let g=new Array(t);for(let d=0;d<t;d++){let h=new Array(i);for(let p=0;p<i;p++){let x=l*(p+d*i),y=b.subarray(x,x+l);h[p]=O(Jo(y),n)}g[d]=h}return g}function cn(e,t){let r=t.map(n=>Array.from(n).reverse());return(n,o)=>{let[i,a,s,c]=r.map(f=>f.reduce((u,l)=>e.add(e.mul(u,n),l)));return n=e.div(i,a),o=e.mul(o,e.div(s,c)),{x:n,y:o}}}function ln(e,t,r){if(typeof t!="function")throw new Error("mapToCurve() must be defined");return{hashToCurve(n,o){let i=an(n,2,{...r,DST:r.DST,...o}),a=e.fromAffine(t(i[0])),s=e.fromAffine(t(i[1])),c=a.add(s).clearCofactor();return c.assertValidity(),c},encodeToCurve(n,o){let i=an(n,1,{...r,DST:r.encodeDST,...o}),a=e.fromAffine(t(i[0])).clearCofactor();return a.assertValidity(),a}}}function ti(e){return{hash:e,hmac:(t,...r)=>me(e,t,_e(...r)),randomBytes:$e}}function fn(e,t){let r=n=>on({...e,...ti(n)});return Object.freeze({...r(t),create:r})}var yt=BigInt("0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"),bt=BigInt("0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"),hn=BigInt(1),mt=BigInt(2),un=(e,t)=>(e+t/mt)/t;function pn(e){let t=yt,r=BigInt(3),n=BigInt(6),o=BigInt(11),i=BigInt(22),a=BigInt(23),s=BigInt(44),c=BigInt(88),f=e*e*e%t,u=f*f*e%t,l=Y(u,r,t)*u%t,m=Y(l,r,t)*u%t,b=Y(m,mt,t)*f%t,g=Y(b,o,t)*b%t,d=Y(g,i,t)*g%t,h=Y(d,s,t)*d%t,p=Y(h,c,t)*h%t,x=Y(p,s,t)*d%t,y=Y(x,r,t)*u%t,k=Y(y,a,t)*g%t,B=Y(k,n,t)*f%t,v=Y(B,mt,t);if(!Se.eql(Se.sqr(v),e))throw new Error("Cannot find square root");return v}var Se=Fr(yt,void 0,void 0,{sqrt:pn}),M=fn({a:BigInt(0),b:BigInt(7),Fp:Se,n:bt,Gx:BigInt("55066263022277343669578718895168534326250603453777594175500187360389116729240"),Gy:BigInt("32670510020758816978083085130507043184471273380659243275938904335757337482424"),h:BigInt(1),lowS:!0,endo:{beta:BigInt("0x7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee"),splitScalar:e=>{let t=bt,r=BigInt("0x3086d221a7d46bcde86c90e49284eb15"),n=-hn*BigInt("0xe4437ed6010e88286f547fa90abfe4c3"),o=BigInt("0x114ca50f7a8e2f3f657c1108d9d44cfd8"),i=r,a=BigInt("0x100000000000000000000000000000000"),s=un(i*e,t),c=un(-n*e,t),f=O(e-s*r-c*o,t),u=O(-s*n-c*i,t),l=f>a,m=u>a;if(l&&(f=t-f),m&&(u=t-u),f>a||u>a)throw new Error("splitScalar: Endomorphism failed, k="+e);return{k1neg:l,k1:f,k2neg:m,k2:u}}}},re),wt=BigInt(0),bn=e=>typeof e=="bigint"&&wt<e&&e<yt,ri=e=>typeof e=="bigint"&&wt<e&&e<bt,dn={};function gt(e,...t){let r=dn[e];if(r===void 0){let n=re(Uint8Array.from(e,o=>o.charCodeAt(0)));r=P(n,n),dn[e]=r}return re(P(r,...t))}var Wt=e=>e.toRawBytes(!0).slice(1),Zt=e=>oe(e,32),Mt=e=>O(e,yt),Xe=e=>O(e,bt),Yt=M.ProjectivePoint,ni=(e,t,r)=>Yt.BASE.multiplyAndAddUnsafe(e,t,r);function Gt(e){let t=M.utils.normPrivateKeyToScalar(e),r=Yt.fromPrivateKey(t);return{scalar:r.hasEvenY()?t:Xe(-t),bytes:Wt(r)}}function mn(e){if(!bn(e))throw new Error("bad x: need 0 < x < p");let t=Mt(e*e),r=Mt(t*e+BigInt(7)),n=pn(r);n%mt!==wt&&(n=Mt(-n));let o=new Yt(e,n,hn);return o.assertValidity(),o}function gn(...e){return Xe(K(gt("BIP0340/challenge",...e)))}function oi(e){return Gt(e).bytes}function ii(e,t,r=$e(32)){let n=R("message",e),{bytes:o,scalar:i}=Gt(t),a=R("auxRand",r,32),s=Zt(i^K(gt("BIP0340/aux",a))),c=gt("BIP0340/nonce",s,o,n),f=Xe(K(c));if(f===wt)throw new Error("sign failed: k is zero");let{bytes:u,scalar:l}=Gt(f),m=gn(u,o,n),b=new Uint8Array(64);if(b.set(u,0),b.set(Zt(Xe(l+m*i)),32),!yn(b,n,o))throw new Error("sign: Invalid signature produced");return b}function yn(e,t,r){let n=R("signature",e,64),o=R("message",t),i=R("publicKey",r,32);try{let a=mn(K(i)),s=K(n.subarray(0,32));if(!bn(s))return!1;let c=K(n.subarray(32,64));if(!ri(c))return!1;let f=gn(Zt(s),Wt(a),o),u=ni(a,c,Xe(-f));return!(!u||!u.hasEvenY()||u.toAffine().x!==s)}catch{return!1}}var si={getPublicKey:oi,sign:ii,verify:yn,utils:{randomPrivateKey:M.utils.randomPrivateKey,lift_x:mn,pointToBytes:Wt,numberToBytesBE:oe,bytesToNumberBE:K,taggedHash:gt,mod:O}},ai=cn(Se,[["0x8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38daaaaa8c7","0x7d3d4c80bc321d5b9f315cea7fd44c5d595d2fc0bf63b92dfff1044f17c6581","0x534c328d23f234e6e2a413deca25caece4506144037c40314ecbd0b53d9dd262","0x8e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38e38daaaaa88c"],["0xd35771193d94918a9ca34ccbb7b640dd86cd409542f8487d9fe6b745781eb49b","0xedadc6f64383dc1df7c4b2d51b54225406d36b641f5e41bbc52a56612a8c6d14","0x0000000000000000000000000000000000000000000000000000000000000001"],["0x4bda12f684bda12f684bda12f684bda12f684bda12f684bda12f684b8e38e23c","0xc75e0c32d5cb7c0fa9d0a54b12a0a6d5647ab046d686da6fdffc90fc201d71a3","0x29a6194691f91a73715209ef6512e576722830a201be2018a765e85a9ecee931","0x2f684bda12f684bda12f684bda12f684bda12f684bda12f684bda12f38e38d84"],["0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffff93b","0x7a06534bb8bdb49fd5e9e6632722c2989467c1bfc8e8d978dfb425d2685c2573","0x6484aa716545ca2cf3a70c3fa8fe337e0a3d21162f0d6299a7bf8192bfd2a76f","0x0000000000000000000000000000000000000000000000000000000000000001"]].map(e=>e.map(t=>BigInt(t)))),ci=sn(Se,{A:BigInt("0x3f8731abdd661adca08a5558f0f5d272e953d363cb6f0e5d405447c01a444533"),B:BigInt("1771"),Z:Se.create(BigInt("-11"))}),wn=ln(M.ProjectivePoint,e=>{let{x:t,y:r}=ci(Se.create(e[0]));return ai(t,r)},{DST:"secp256k1_XMD:SHA-256_SSWU_RO_",encodeDST:"secp256k1_XMD:SHA-256_SSWU_NU_",p:Se.ORDER,m:1,k:128,expand:"xmd",hash:re}),li=wn.hashToCurve,fi=wn.encodeToCurve;var xt=M.ProjectivePoint,Xt=st(re);function vn(e){return BigInt(`0x${or(e)}`)}function ui(e){return ir(e.toString(16).padStart(64,"0"))}var di=kt("Bitcoin seed"),Jt={private:76066276,public:76067358},Et=2147483648,hi=e=>Ot(re(e)),pi=e=>ee(e).getUint32(0,!1),vt=e=>{if(!Number.isSafeInteger(e)||e<0||e>2**32-1)throw new Error(`Invalid number=${e}. Should be from 0 to 2 ** 32 - 1`);let t=new Uint8Array(4);return ee(t).setUint32(0,e,!1),t},Qt=class e{get fingerprint(){if(!this.pubHash)throw new Error("No publicKey set!");return pi(this.pubHash)}get identifier(){return this.pubHash}get pubKeyHash(){return this.pubHash}get privateKey(){return this.privKeyBytes||null}get publicKey(){return this.pubKey||null}get privateExtendedKey(){let t=this.privateKey;if(!t)throw new Error("No private key");return Xt.encode(this.serialize(this.versions.private,_e(new Uint8Array([0]),t)))}get publicExtendedKey(){if(!this.pubKey)throw new Error("No public key");return Xt.encode(this.serialize(this.versions.public,this.pubKey))}static fromMasterSeed(t,r=Jt){if(V(t),8*t.length<128||8*t.length>512)throw new Error(`HDKey: wrong seed length=${t.length}. Should be between 128 and 512 bits; 256 bits is advised)`);let n=me(je,di,t);return new e({versions:r,chainCode:n.slice(32),privateKey:n.slice(0,32)})}static fromExtendedKey(t,r=Jt){let n=Xt.decode(t),o=ee(n),i=o.getUint32(0,!1),a={versions:r,depth:n[4],parentFingerprint:o.getUint32(5,!1),index:o.getUint32(9,!1),chainCode:n.slice(13,45)},s=n.slice(45),c=s[0]===0;if(i!==r[c?"private":"public"])throw new Error("Version mismatch");return c?new e({...a,privateKey:s.slice(1)}):new e({...a,publicKey:s})}static fromJSON(t){return e.fromExtendedKey(t.xpriv)}constructor(t){if(this.depth=0,this.index=0,this.chainCode=null,this.parentFingerprint=0,!t||typeof t!="object")throw new Error("HDKey.constructor must not be called directly");if(this.versions=t.versions||Jt,this.depth=t.depth||0,this.chainCode=t.chainCode||null,this.index=t.index||0,this.parentFingerprint=t.parentFingerprint||0,!this.depth&&(this.parentFingerprint||this.index))throw new Error("HDKey: zero depth with non-zero index/parent fingerprint");if(t.publicKey&&t.privateKey)throw new Error("HDKey: publicKey and privateKey at same time.");if(t.privateKey){if(!M.utils.isValidPrivateKey(t.privateKey))throw new Error("Invalid private key");this.privKey=typeof t.privateKey=="bigint"?t.privateKey:vn(t.privateKey),this.privKeyBytes=ui(this.privKey),this.pubKey=M.getPublicKey(t.privateKey,!0)}else if(t.publicKey)this.pubKey=xt.fromHex(t.publicKey).toRawBytes(!0);else throw new Error("HDKey: no public or private key provided");this.pubHash=hi(this.pubKey)}derive(t){if(!/^[mM]'?/.test(t))throw new Error('Path must start with "m" or "M"');if(/^[mM]'?$/.test(t))return this;let r=t.replace(/^[mM]'?\//,"").split("/"),n=this;for(let o of r){let i=/^(\d+)('?)$/.exec(o),a=i&&i[1];if(!i||i.length!==3||typeof a!="string")throw new Error(`Invalid child index: ${o}`);let s=+a;if(!Number.isSafeInteger(s)||s>=Et)throw new Error("Invalid index");i[2]==="'"&&(s+=Et),n=n.deriveChild(s)}return n}deriveChild(t){if(!this.pubKey||!this.chainCode)throw new Error("No publicKey or chainCode set");let r=vt(t);if(t>=Et){let s=this.privateKey;if(!s)throw new Error("Could not derive hardened child key");r=_e(new Uint8Array([0]),s,r)}else r=_e(this.pubKey,r);let n=me(je,this.chainCode,r),o=vn(n.slice(0,32)),i=n.slice(32);if(!M.utils.isValidPrivateKey(o))throw new Error("Tweak bigger than curve order");let a={versions:this.versions,chainCode:i,depth:this.depth+1,parentFingerprint:this.fingerprint,index:t};try{if(this.privateKey){let s=O(this.privKey+o,M.CURVE.n);if(!M.utils.isValidPrivateKey(s))throw new Error("The tweak was out of range or the resulted private key is invalid");a.privateKey=s}else{let s=xt.fromHex(this.pubKey).add(xt.fromPrivateKey(o));if(s.equals(xt.ZERO))throw new Error("The tweak was equal to negative P, which made the result key invalid");a.publicKey=s.toRawBytes(!0)}return new e(a)}catch{return this.deriveChild(t+1)}}sign(t){if(!this.privateKey)throw new Error("No privateKey set!");return V(t,32),M.sign(t,this.privKey).toCompactRawBytes()}verify(t,r){if(V(t,32),V(r,64),!this.publicKey)throw new Error("No publicKey set!");let n;try{n=M.Signature.fromCompact(r)}catch{return!1}return M.verify(n,t,this.publicKey)}wipePrivateData(){return this.privKey=void 0,this.privKeyBytes&&(this.privKeyBytes.fill(0),this.privKeyBytes=void 0),this}toJSON(){return{xpriv:this.privateExtendedKey,xpub:this.publicExtendedKey}}serialize(t,r){if(!this.chainCode)throw new Error("No chainCode set");return V(r,33),_e(vt(t),new Uint8Array([this.depth]),vt(this.parentFingerprint),vt(this.index),this.chainCode,r)}};export{Nr as base,En as bip32,zr as bip39,wo as english,Zr as rip,xn as secp,pr as sha};
/*! Bundled license information:

@noble/hashes/esm/utils.js:
  (*! noble-hashes - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/base/lib/esm/index.js:
  (*! scure-base - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/bip39/esm/index.js:
  (*! scure-bip39 - MIT License (c) 2022 Patricio Palladino, Paul Miller (paulmillr.com) *)

@noble/curves/esm/abstract/utils.js:
@noble/curves/esm/abstract/modular.js:
@noble/curves/esm/abstract/curve.js:
@noble/curves/esm/abstract/weierstrass.js:
@noble/curves/esm/_shortw_utils.js:
@noble/curves/esm/secp256k1.js:
  (*! noble-curves - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/bip32/lib/esm/index.js:
  (*! scure-bip32 - MIT License (c) 2022 Patricio Palladino, Paul Miller (paulmillr.com) *)
*/
